using GTweens.Builders;
using GTweens.Easings;
using GTweens.Extensions;
using GTweens.Tweens;
using Quartz.Async;
using Quartz.Core;
using Quartz.Core.Service;
using Quartz.IO;
using Quartz.Localization;
using Quartz.Resource;
using Quartz.Tween;
using Quartz.UI.Generator;
using Quartz.UI.Objects.Impl;
using Quartz.UI.Utility;
using Quartz.Utility;
using Quartz.Update;
using UnityEngine;
using UnityEngine.UI;
using GTweenExtensions = GTweens.Extensions.GTweenExtensions;
using TMPro;
namespace Quartz.UI.Factory.Page;
internal static partial class PageSettings {
    private static UIDropDown<string> languageDropdown;
    private static UIDropDown<string> fontDropdown;
    private static GameObject fontManageRow;
    private static UIInput fontRenameInput;
    private static UIButton fontDeleteBtn;
    private static Func<Color> fontDeleteRestColor;
    private static bool fontDeleteArmed;
    private static GameObject fontStatusRow;
    private static TextMeshProUGUI fontStatusText;
    private static UIDropDown<string> settingsFontDropdown;
    private static string pendingFontName = "";
    private static UIButton updateCheckButton;
    private static TextMeshProUGUI updateStatusText;
    private static GameObject updateActionRow;
    private static GameObject updateButtonRow;
    private static TextMeshProUGUI updateVersionText;
    private static UIButton updateNotesButton;
    private static UIButton updateSkipButton;
    private static UIButton updateInstallButton;
    private static UIButton updateUndoButton;
    private static GameObject updateProgressRow;
    private static RectTransform updateProgressFill;
    private static TextMeshProUGUI updateProgressLabel;
    private static bool updateHooked;
    private static UIScrollController scrollController;
    private static RectTransform pageContent;
    private static RectTransform updatesAnchor;
    public static void Create(RectTransform parent) {
        FontManager.OnFontCatalogChanged -= RefreshFontDropdowns;
        FontManager.OnFontCatalogChanged += RefreshFontDropdowns;
        RectTransform content = Quartz.UI.Factory.PageFactory.CreateScrollablePage(parent, out scrollController);
        pageContent = content;
        CoreSettings defSet = new();
        CreateLanguageSection(content, defSet);
        CreateBehaviourSection(content, defSet);
        CreateAppearanceSection(content, defSet);
        CreateUpdatesSection(content, defSet);
        CreateFontSection(content, defSet);
    }
}
