// <auto-generated>
//   Compile-only stand-in for "0Harmony", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace HarmonyLib {
    public static unsafe partial class AccessTools {
        public static global::System.Reflection.FieldInfo Field(global::System.Type type, string name) => throw null;
        public static global::HarmonyLib.AccessTools.FieldRef<T, F> FieldRefAccess<T, F>(string fieldName) => throw null;
        public static global::HarmonyLib.AccessTools.FieldRef<T, F> FieldRefAccess<T, F>(global::System.Reflection.FieldInfo fieldInfo) => throw null;
        public static global::System.Collections.Generic.List<global::System.Reflection.MethodInfo> GetDeclaredMethods(global::System.Type type) => throw null;
        public static global::System.Collections.Generic.List<string> GetMethodNames(global::System.Type type) => throw null;
        public static global::System.Type[] GetTypesFromAssembly(global::System.Reflection.Assembly assembly) => throw null;
        public static global::System.Type Inner(global::System.Type type, string name) => throw null;
        public static global::System.Reflection.MethodInfo Method(global::System.Type type, string name, global::System.Type[] parameters = default, global::System.Type[] generics = default) => throw null;
        public static global::System.Reflection.PropertyInfo Property(global::System.Type type, string name) => throw null;
        public static global::System.Reflection.MethodInfo PropertyGetter(global::System.Type type, string name) => throw null;
        public static global::HarmonyLib.AccessTools.FieldRef<F> StaticFieldRefAccess<F>(global::System.Reflection.FieldInfo fieldInfo) => throw null;
        public static global::System.Type TypeByName(string name) => throw null;
        public unsafe delegate ref F FieldRef<T, F>(T instance = default);
        public unsafe delegate ref F FieldRef<F>();
    }
    public unsafe partial class CodeInstruction {
        public global::System.Reflection.Emit.OpCode opcode;
        public object operand;
        public CodeInstruction(global::System.Reflection.Emit.OpCode opcode, object operand = default) => throw null;
        protected CodeInstruction() { }
    }
    public static unsafe partial class CodeInstructionExtensions {
        public static global::HarmonyLib.CodeInstruction MoveLabelsFrom(this global::HarmonyLib.CodeInstruction code, global::HarmonyLib.CodeInstruction other) => throw null;
    }
    public unsafe partial class Harmony {
        public string Id { get => throw null; }
        public Harmony(string id) => throw null;
        public global::HarmonyLib.PatchClassProcessor CreateClassProcessor(global::System.Type type) => throw null;
        public global::HarmonyLib.PatchProcessor CreateProcessor(global::System.Reflection.MethodBase original) => throw null;
        public static global::HarmonyLib.Patches GetPatchInfo(global::System.Reflection.MethodBase method) => throw null;
        public global::System.Collections.Generic.IEnumerable<global::System.Reflection.MethodBase> GetPatchedMethods() => throw null;
        public global::System.Reflection.MethodInfo Patch(global::System.Reflection.MethodBase original, global::HarmonyLib.HarmonyMethod prefix = default, global::HarmonyLib.HarmonyMethod postfix = default, global::HarmonyLib.HarmonyMethod transpiler = default, global::HarmonyLib.HarmonyMethod finalizer = default) => throw null;
        public void PatchAll(global::System.Reflection.Assembly assembly) => throw null;
        public void Unpatch(global::System.Reflection.MethodBase original, global::System.Reflection.MethodInfo patch) => throw null;
        public void Unpatch(global::System.Reflection.MethodBase original, global::HarmonyLib.HarmonyPatchType type, string harmonyID = default) => throw null;
        protected Harmony() { }
    }
    public unsafe partial class HarmonyAttribute : global::System.Attribute {
        protected HarmonyAttribute() { }
    }
    public unsafe partial class HarmonyMethod {
        public string[] after;
        public string[] before;
        public int priority;
        public HarmonyMethod(global::System.Reflection.MethodInfo method) => throw null;
        protected HarmonyMethod() { }
    }
    public unsafe partial class HarmonyPatch : global::HarmonyLib.HarmonyAttribute {
        public HarmonyPatch() => throw null;
        public HarmonyPatch(global::System.Type declaringType, string methodName) => throw null;
        public HarmonyPatch(global::System.Type declaringType, string methodName, params global::System.Type[] argumentTypes) => throw null;
        public HarmonyPatch(global::System.Type declaringType, string methodName, global::HarmonyLib.MethodType methodType) => throw null;
    }
    public enum HarmonyPatchType : int {
        All = 0,
        Prefix = 1,
        Postfix = 2,
        Transpiler = 3,
        Finalizer = 4,
        ReversePatch = 5,
    }
    public enum MethodType : int {
        Normal = 0,
        Getter = 1,
        Setter = 2,
        Constructor = 3,
        StaticConstructor = 4,
        Enumerator = 5,
        Async = 6,
    }
    public unsafe partial class Patch {
        public readonly string[] after;
        public readonly string[] before;
        public readonly string owner;
        public readonly int priority;
        public global::System.Reflection.MethodInfo PatchMethod { get => throw null; set { } }
        protected Patch() { }
    }
    public unsafe partial class PatchClassProcessor {
        public global::System.Collections.Generic.List<global::System.Reflection.MethodInfo> Patch() => throw null;
        protected PatchClassProcessor() { }
    }
    public unsafe partial class PatchProcessor {
        public global::HarmonyLib.PatchProcessor AddPrefix(global::HarmonyLib.HarmonyMethod prefix) => throw null;
        public global::System.Reflection.MethodInfo Patch() => throw null;
        protected PatchProcessor() { }
    }
    public unsafe partial class Patches {
        public readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::HarmonyLib.Patch> Finalizers;
        public readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::HarmonyLib.Patch> Postfixes;
        public readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::HarmonyLib.Patch> Prefixes;
        public readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::HarmonyLib.Patch> Transpilers;
        public global::System.Collections.ObjectModel.ReadOnlyCollection<string> Owners { get => throw null; }
        protected Patches() { }
    }
    public unsafe partial class Traverse {
        public static global::HarmonyLib.Traverse Create(object root) => throw null;
        public global::HarmonyLib.Traverse Field(string name) => throw null;
        public bool FieldExists() => throw null;
        public object GetValue() => throw null;
        public T GetValue<T>() => throw null;
        public global::HarmonyLib.Traverse Method(string name, params object[] arguments) => throw null;
        public global::HarmonyLib.Traverse Property(string name, object[] index = default) => throw null;
        public global::HarmonyLib.Traverse SetValue(object value) => throw null;
        protected Traverse() { }
    }
}
