// <auto-generated>
//   Compile-only stand-in for "MelonLoader", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace MelonLoader {
    public unsafe partial class HarmonyDontPatchAllAttribute : global::System.Attribute {
        public HarmonyDontPatchAllAttribute() => throw null;
    }
    public abstract unsafe partial class MelonBase {
        public global::MelonLoader.MelonInfoAttribute Info { get => throw null; }
        public virtual void OnDeinitializeMelon() => throw null;
        public virtual void OnInitializeMelon() => throw null;
        public virtual void OnUpdate() => throw null;
        protected MelonBase() { }
        public enum Incompatibility : int {
            MLVersion = 0,
            MLBuild = 1,
            Game = 2,
            GameVersion = 3,
            ProcessName = 4,
            Domain = 5,
            Platform = 6,
        }
    }
    public unsafe partial class MelonGameAttribute : global::System.Attribute {
        public MelonGameAttribute(string developer = default, string name = default) => throw null;
        protected MelonGameAttribute() { }
    }
    public unsafe partial class MelonInfoAttribute : global::System.Attribute {
        public string Name { get => throw null; }
        public MelonInfoAttribute(global::System.Type type, string name, string version, string author, string downloadLink = default) => throw null;
        protected MelonInfoAttribute() { }
    }
    public unsafe partial class MelonLogger {
        public static void Error(string txt) => throw null;
        public static void Msg(string txt) => throw null;
        public static void Warning(string txt) => throw null;
        protected MelonLogger() { }
    }
    public abstract unsafe partial class MelonMod : global::MelonLoader.MelonTypeBase<global::MelonLoader.MelonMod> {
        protected MelonMod() => throw null;
    }
    public abstract unsafe partial class MelonTypeBase<T> : global::MelonLoader.MelonBase where T : global::MelonLoader.MelonTypeBase<T> {
        protected MelonTypeBase() { }
    }
}
namespace MelonLoader.Utils {
    public static unsafe partial class MelonEnvironment {
        public static string ModsDirectory { get => throw null; }
        public static string UserDataDirectory { get => throw null; }
        public static string UserLibsDirectory { get => throw null; }
    }
}
