// <auto-generated>
//   Compile-only stand-in for "UnityEngine.CoreModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine {
    public unsafe partial class AnimationCurve : global::System.IEquatable<global::UnityEngine.AnimationCurve> {
        protected AnimationCurve() { }
        bool global::System.IEquatable<global::UnityEngine.AnimationCurve>.Equals(global::UnityEngine.AnimationCurve other) => throw null;
    }
    public unsafe partial class Application {
        public static string dataPath { get => throw null; }
        public static bool isFocused { get => throw null; }
        public static global::UnityEngine.RuntimePlatform platform { get => throw null; }
        public static bool runInBackground { get => throw null; set { } }
        public static global::UnityEngine.SystemLanguage systemLanguage { get => throw null; }
        public static void OpenURL(string url) => throw null;
        public static void Quit() => throw null;
        protected Application() { }
    }
    public unsafe partial class Behaviour : global::UnityEngine.Component {
        public bool enabled { get => throw null; set { } }
        public bool isActiveAndEnabled { get => throw null; }
        protected Behaviour() { }
    }
    public unsafe partial struct Bounds : global::System.IEquatable<global::UnityEngine.Bounds> {
        private global::UnityEngine.Vector3 m_Center;
        private global::UnityEngine.Vector3 m_Extents;
        public global::UnityEngine.Vector3 size { get => throw null; set { } }
        bool global::System.IEquatable<global::UnityEngine.Bounds>.Equals(global::UnityEngine.Bounds other) => throw null;
    }
    public sealed unsafe partial class Camera : global::UnityEngine.Behaviour {
        public const float kMaxAperture = 0f;
        public const int kMaxBladeCount = 1;
        public const float kMinAperture = 2f;
        public const int kMinBladeCount = 3;
        public global::UnityEngine.CameraClearFlags clearFlags { get => throw null; set { } }
        private Camera() { }
        public enum GateFitMode : int {
            Vertical = 1,
            Horizontal = 2,
            Fill = 3,
            Overscan = 4,
            None = 0,
        }
        public enum FieldOfViewAxis : int {
            Vertical = 0,
            Horizontal = 1,
        }
        public enum StereoscopicEye : int {
            Left = 0,
            Right = 1,
        }
        public enum MonoOrStereoscopicEye : int {
            Left = 0,
            Right = 1,
            Mono = 2,
        }
        public enum SceneViewFilterMode : int {
            Off = 0,
            ShowFiltered = 1,
        }
    }
    public enum CameraClearFlags : int {
        Skybox = 1,
        Color = 2,
        SolidColor = 2,
        Depth = 3,
        Nothing = 4,
    }
    public unsafe partial struct Color : global::System.IEquatable<global::UnityEngine.Color> {
        public float a;
        public float b;
        public float g;
        public float r;
        public float this[int index] { get => throw null; set { } }
        public static global::UnityEngine.Color black { get => throw null; }
        public static global::UnityEngine.Color blue { get => throw null; }
        public static global::UnityEngine.Color clear { get => throw null; }
        public static global::UnityEngine.Color magenta { get => throw null; }
        public static global::UnityEngine.Color red { get => throw null; }
        public static global::UnityEngine.Color white { get => throw null; }
        public Color(float r, float g, float b) => throw null;
        public Color(float r, float g, float b, float a) => throw null;
        public static global::UnityEngine.Color HSVToRGB(float H, float S, float V) => throw null;
        public static global::UnityEngine.Color Lerp(global::UnityEngine.Color a, global::UnityEngine.Color b, float t) => throw null;
        public static void RGBToHSV(global::UnityEngine.Color rgbColor, out float H, out float S, out float V) => throw null;
        public static global::UnityEngine.Color operator +(global::UnityEngine.Color a, global::UnityEngine.Color b) => throw null;
        public static bool operator ==(global::UnityEngine.Color lhs, global::UnityEngine.Color rhs) => throw null;
        public static bool operator !=(global::UnityEngine.Color lhs, global::UnityEngine.Color rhs) => throw null;
        public static global::UnityEngine.Color operator *(global::UnityEngine.Color a, float b) => throw null;
        public static global::UnityEngine.Color operator *(global::UnityEngine.Color a, global::UnityEngine.Color b) => throw null;
        public override bool Equals(object obj) => throw null;
        public override int GetHashCode() => throw null;
        bool global::System.IEquatable<global::UnityEngine.Color>.Equals(global::UnityEngine.Color other) => throw null;
    }
    public unsafe partial struct Color32 : global::System.IEquatable<global::UnityEngine.Color32> {
        public byte a;
        public byte b;
        public byte g;
        public byte r;
        private int rgba;
        public Color32(byte r, byte g, byte b, byte a) => throw null;
        public static implicit operator global::UnityEngine.Color32(global::UnityEngine.Color c) => throw null;
        public static implicit operator global::UnityEngine.Color(global::UnityEngine.Color32 c) => throw null;
        bool global::System.IEquatable<global::UnityEngine.Color32>.Equals(global::UnityEngine.Color32 other) => throw null;
    }
    public unsafe partial class ColorUtility {
        public static string ToHtmlStringRGB(global::UnityEngine.Color color) => throw null;
        public static string ToHtmlStringRGBA(global::UnityEngine.Color color) => throw null;
        public static bool TryParseHtmlString(string htmlString, out global::UnityEngine.Color color) => throw null;
        protected ColorUtility() { }
    }
    public unsafe partial class Component : global::UnityEngine.Object {
        public global::UnityEngine.GameObject gameObject { get => throw null; }
        public global::UnityEngine.Transform transform { get => throw null; }
        public T GetComponent<T>() => throw null;
        public global::UnityEngine.Component GetComponent(string type) => throw null;
        public T GetComponentInChildren<T>() => throw null;
        public T GetComponentInChildren<T>(bool includeInactive) => throw null;
        public T GetComponentInParent<T>() => throw null;
        public T[] GetComponents<T>() => throw null;
        public T[] GetComponentsInChildren<T>(bool includeInactive) => throw null;
        public bool TryGetComponent<T>(out T component) => throw null;
        protected Component() { }
    }
    public sealed unsafe partial class Coroutine : global::UnityEngine.YieldInstruction {
        private Coroutine() { }
    }
    public unsafe partial class Cursor {
        public static global::UnityEngine.CursorLockMode lockState { get => throw null; set { } }
        public static bool visible { get => throw null; set { } }
        public static void SetCursor(global::UnityEngine.Texture2D texture, global::UnityEngine.Vector2 hotspot, global::UnityEngine.CursorMode cursorMode) => throw null;
        protected Cursor() { }
    }
    public enum CursorLockMode : int {
        None = 0,
        Locked = 1,
        Confined = 2,
    }
    public enum CursorMode : int {
        Auto = 0,
        ForceSoftware = 1,
    }
    public unsafe partial class DefaultExecutionOrder : global::System.Attribute {
        public DefaultExecutionOrder(int order) => throw null;
        protected DefaultExecutionOrder() { }
    }
    public unsafe partial struct EntityId : global::System.IEquatable<global::UnityEngine.EntityId>, global::System.IComparable<global::UnityEngine.EntityId> {
        private int m_Data;
        int global::System.IComparable<global::UnityEngine.EntityId>.CompareTo(global::UnityEngine.EntityId other) => throw null;
        bool global::System.IEquatable<global::UnityEngine.EntityId>.Equals(global::UnityEngine.EntityId other) => throw null;
    }
    public enum FilterMode : int {
        Point = 0,
        Bilinear = 1,
        Trilinear = 2,
    }
    public enum FindObjectsSortMode : int {
        None = 0,
        InstanceID = 1,
    }
    public sealed unsafe partial class GameObject : global::UnityEngine.Object {
        public bool activeInHierarchy { get => throw null; }
        public bool activeSelf { get => throw null; }
        public int layer { get => throw null; set { } }
        public global::UnityEngine.Transform transform { get => throw null; }
        public GameObject() => throw null;
        public GameObject(string name) => throw null;
        public GameObject(string name, params global::System.Type[] components) => throw null;
        public T AddComponent<T>() where T : global::UnityEngine.Component => throw null;
        public T GetComponent<T>() => throw null;
        public T GetComponentInChildren<T>(bool includeInactive) => throw null;
        public T GetComponentInParent<T>() => throw null;
        public T[] GetComponentsInChildren<T>(bool includeInactive) => throw null;
        public void SetActive(bool value) => throw null;
    }
    public unsafe partial class Gradient : global::System.IEquatable<global::UnityEngine.Gradient> {
        protected Gradient() { }
        bool global::System.IEquatable<global::UnityEngine.Gradient>.Equals(global::UnityEngine.Gradient other) => throw null;
    }
    public unsafe partial class Graphics {
        public static void Blit(global::UnityEngine.Texture source, global::UnityEngine.RenderTexture dest) => throw null;
        protected Graphics() { }
    }
    public enum HideFlags : int {
        None = 0,
        HideInHierarchy = 1,
        HideInInspector = 2,
        DontSaveInEditor = 4,
        NotEditable = 8,
        DontSaveInBuild = 16,
        DontUnloadUnusedAsset = 32,
        DontSave = 52,
        HideAndDontSave = 61,
    }
    public unsafe partial interface ISerializationCallbackReceiver {
    }
    public enum KeyCode : int {
        None = 0,
        Backspace = 8,
        Delete = 127,
        Tab = 9,
        Clear = 12,
        Return = 13,
        Pause = 19,
        Escape = 27,
        Space = 32,
        Keypad0 = 256,
        Keypad1 = 257,
        Keypad2 = 258,
        Keypad3 = 259,
        Keypad4 = 260,
        Keypad5 = 261,
        Keypad6 = 262,
        Keypad7 = 263,
        Keypad8 = 264,
        Keypad9 = 265,
        KeypadPeriod = 266,
        KeypadDivide = 267,
        KeypadMultiply = 268,
        KeypadMinus = 269,
        KeypadPlus = 270,
        KeypadEnter = 271,
        KeypadEquals = 272,
        UpArrow = 273,
        DownArrow = 274,
        RightArrow = 275,
        LeftArrow = 276,
        Insert = 277,
        Home = 278,
        End = 279,
        PageUp = 280,
        PageDown = 281,
        F1 = 282,
        F2 = 283,
        F3 = 284,
        F4 = 285,
        F5 = 286,
        F6 = 287,
        F7 = 288,
        F8 = 289,
        F9 = 290,
        F10 = 291,
        F11 = 292,
        F12 = 293,
        F13 = 294,
        F14 = 295,
        F15 = 296,
        Alpha0 = 48,
        Alpha1 = 49,
        Alpha2 = 50,
        Alpha3 = 51,
        Alpha4 = 52,
        Alpha5 = 53,
        Alpha6 = 54,
        Alpha7 = 55,
        Alpha8 = 56,
        Alpha9 = 57,
        Exclaim = 33,
        DoubleQuote = 34,
        Hash = 35,
        Dollar = 36,
        Percent = 37,
        Ampersand = 38,
        Quote = 39,
        LeftParen = 40,
        RightParen = 41,
        Asterisk = 42,
        Plus = 43,
        Comma = 44,
        Minus = 45,
        Period = 46,
        Slash = 47,
        Colon = 58,
        Semicolon = 59,
        Less = 60,
        Equals = 61,
        Greater = 62,
        Question = 63,
        At = 64,
        LeftBracket = 91,
        Backslash = 92,
        RightBracket = 93,
        Caret = 94,
        Underscore = 95,
        BackQuote = 96,
        A = 97,
        B = 98,
        C = 99,
        D = 100,
        E = 101,
        F = 102,
        G = 103,
        H = 104,
        I = 105,
        J = 106,
        K = 107,
        L = 108,
        M = 109,
        N = 110,
        O = 111,
        P = 112,
        Q = 113,
        R = 114,
        S = 115,
        T = 116,
        U = 117,
        V = 118,
        W = 119,
        X = 120,
        Y = 121,
        Z = 122,
        LeftCurlyBracket = 123,
        Pipe = 124,
        RightCurlyBracket = 125,
        Tilde = 126,
        Numlock = 300,
        CapsLock = 301,
        ScrollLock = 302,
        RightShift = 303,
        LeftShift = 304,
        RightControl = 305,
        LeftControl = 306,
        RightAlt = 307,
        LeftAlt = 308,
        LeftMeta = 310,
        LeftCommand = 310,
        LeftApple = 310,
        LeftWindows = 311,
        RightMeta = 309,
        RightCommand = 309,
        RightApple = 309,
        RightWindows = 312,
        AltGr = 313,
        Help = 315,
        Print = 316,
        SysReq = 317,
        Break = 318,
        Menu = 319,
        WheelUp = 321,
        WheelDown = 322,
        F16 = 670,
        F17 = 671,
        F18 = 672,
        F19 = 673,
        F20 = 674,
        F21 = 675,
        F22 = 676,
        F23 = 677,
        F24 = 678,
        Mouse0 = 323,
        Mouse1 = 324,
        Mouse2 = 325,
        Mouse3 = 326,
        Mouse4 = 327,
        Mouse5 = 328,
        Mouse6 = 329,
        JoystickButton0 = 330,
        JoystickButton1 = 331,
        JoystickButton2 = 332,
        JoystickButton3 = 333,
        JoystickButton4 = 334,
        JoystickButton5 = 335,
        JoystickButton6 = 336,
        JoystickButton7 = 337,
        JoystickButton8 = 338,
        JoystickButton9 = 339,
        JoystickButton10 = 340,
        JoystickButton11 = 341,
        JoystickButton12 = 342,
        JoystickButton13 = 343,
        JoystickButton14 = 344,
        JoystickButton15 = 345,
        JoystickButton16 = 346,
        JoystickButton17 = 347,
        JoystickButton18 = 348,
        JoystickButton19 = 349,
        Joystick1Button0 = 350,
        Joystick1Button1 = 351,
        Joystick1Button2 = 352,
        Joystick1Button3 = 353,
        Joystick1Button4 = 354,
        Joystick1Button5 = 355,
        Joystick1Button6 = 356,
        Joystick1Button7 = 357,
        Joystick1Button8 = 358,
        Joystick1Button9 = 359,
        Joystick1Button10 = 360,
        Joystick1Button11 = 361,
        Joystick1Button12 = 362,
        Joystick1Button13 = 363,
        Joystick1Button14 = 364,
        Joystick1Button15 = 365,
        Joystick1Button16 = 366,
        Joystick1Button17 = 367,
        Joystick1Button18 = 368,
        Joystick1Button19 = 369,
        Joystick2Button0 = 370,
        Joystick2Button1 = 371,
        Joystick2Button2 = 372,
        Joystick2Button3 = 373,
        Joystick2Button4 = 374,
        Joystick2Button5 = 375,
        Joystick2Button6 = 376,
        Joystick2Button7 = 377,
        Joystick2Button8 = 378,
        Joystick2Button9 = 379,
        Joystick2Button10 = 380,
        Joystick2Button11 = 381,
        Joystick2Button12 = 382,
        Joystick2Button13 = 383,
        Joystick2Button14 = 384,
        Joystick2Button15 = 385,
        Joystick2Button16 = 386,
        Joystick2Button17 = 387,
        Joystick2Button18 = 388,
        Joystick2Button19 = 389,
        Joystick3Button0 = 390,
        Joystick3Button1 = 391,
        Joystick3Button2 = 392,
        Joystick3Button3 = 393,
        Joystick3Button4 = 394,
        Joystick3Button5 = 395,
        Joystick3Button6 = 396,
        Joystick3Button7 = 397,
        Joystick3Button8 = 398,
        Joystick3Button9 = 399,
        Joystick3Button10 = 400,
        Joystick3Button11 = 401,
        Joystick3Button12 = 402,
        Joystick3Button13 = 403,
        Joystick3Button14 = 404,
        Joystick3Button15 = 405,
        Joystick3Button16 = 406,
        Joystick3Button17 = 407,
        Joystick3Button18 = 408,
        Joystick3Button19 = 409,
        Joystick4Button0 = 410,
        Joystick4Button1 = 411,
        Joystick4Button2 = 412,
        Joystick4Button3 = 413,
        Joystick4Button4 = 414,
        Joystick4Button5 = 415,
        Joystick4Button6 = 416,
        Joystick4Button7 = 417,
        Joystick4Button8 = 418,
        Joystick4Button9 = 419,
        Joystick4Button10 = 420,
        Joystick4Button11 = 421,
        Joystick4Button12 = 422,
        Joystick4Button13 = 423,
        Joystick4Button14 = 424,
        Joystick4Button15 = 425,
        Joystick4Button16 = 426,
        Joystick4Button17 = 427,
        Joystick4Button18 = 428,
        Joystick4Button19 = 429,
        Joystick5Button0 = 430,
        Joystick5Button1 = 431,
        Joystick5Button2 = 432,
        Joystick5Button3 = 433,
        Joystick5Button4 = 434,
        Joystick5Button5 = 435,
        Joystick5Button6 = 436,
        Joystick5Button7 = 437,
        Joystick5Button8 = 438,
        Joystick5Button9 = 439,
        Joystick5Button10 = 440,
        Joystick5Button11 = 441,
        Joystick5Button12 = 442,
        Joystick5Button13 = 443,
        Joystick5Button14 = 444,
        Joystick5Button15 = 445,
        Joystick5Button16 = 446,
        Joystick5Button17 = 447,
        Joystick5Button18 = 448,
        Joystick5Button19 = 449,
        Joystick6Button0 = 450,
        Joystick6Button1 = 451,
        Joystick6Button2 = 452,
        Joystick6Button3 = 453,
        Joystick6Button4 = 454,
        Joystick6Button5 = 455,
        Joystick6Button6 = 456,
        Joystick6Button7 = 457,
        Joystick6Button8 = 458,
        Joystick6Button9 = 459,
        Joystick6Button10 = 460,
        Joystick6Button11 = 461,
        Joystick6Button12 = 462,
        Joystick6Button13 = 463,
        Joystick6Button14 = 464,
        Joystick6Button15 = 465,
        Joystick6Button16 = 466,
        Joystick6Button17 = 467,
        Joystick6Button18 = 468,
        Joystick6Button19 = 469,
        Joystick7Button0 = 470,
        Joystick7Button1 = 471,
        Joystick7Button2 = 472,
        Joystick7Button3 = 473,
        Joystick7Button4 = 474,
        Joystick7Button5 = 475,
        Joystick7Button6 = 476,
        Joystick7Button7 = 477,
        Joystick7Button8 = 478,
        Joystick7Button9 = 479,
        Joystick7Button10 = 480,
        Joystick7Button11 = 481,
        Joystick7Button12 = 482,
        Joystick7Button13 = 483,
        Joystick7Button14 = 484,
        Joystick7Button15 = 485,
        Joystick7Button16 = 486,
        Joystick7Button17 = 487,
        Joystick7Button18 = 488,
        Joystick7Button19 = 489,
        Joystick8Button0 = 490,
        Joystick8Button1 = 491,
        Joystick8Button2 = 492,
        Joystick8Button3 = 493,
        Joystick8Button4 = 494,
        Joystick8Button5 = 495,
        Joystick8Button6 = 496,
        Joystick8Button7 = 497,
        Joystick8Button8 = 498,
        Joystick8Button9 = 499,
        Joystick8Button10 = 500,
        Joystick8Button11 = 501,
        Joystick8Button12 = 502,
        Joystick8Button13 = 503,
        Joystick8Button14 = 504,
        Joystick8Button15 = 505,
        Joystick8Button16 = 506,
        Joystick8Button17 = 507,
        Joystick8Button18 = 508,
        Joystick8Button19 = 509,
    }
    public sealed unsafe partial class LineRenderer : global::UnityEngine.Renderer {
        public global::UnityEngine.Color endColor { get => throw null; set { } }
        public global::UnityEngine.Color startColor { get => throw null; set { } }
        private LineRenderer() { }
    }
    public unsafe partial class Material : global::UnityEngine.Object {
        public global::UnityEngine.Color color { get => throw null; set { } }
        public global::UnityEngine.Texture mainTexture { get => throw null; set { } }
        public global::UnityEngine.Shader shader { get => throw null; set { } }
        public Material(global::UnityEngine.Shader shader) => throw null;
        public void DisableKeyword(string keyword) => throw null;
        public void EnableKeyword(string keyword) => throw null;
        public void SetColor(string name, global::UnityEngine.Color value) => throw null;
        public void SetColor(int nameID, global::UnityEngine.Color value) => throw null;
        public void SetFloat(string name, float value) => throw null;
        public void SetFloat(int nameID, float value) => throw null;
        protected Material() { }
    }
    public unsafe partial struct Mathf {
        public const float Deg2Rad = 4f;
        public const float Infinity = 5f;
        public const float NegativeInfinity = 6f;
        public const float PI = 7f;
        public const float Rad2Deg = 8f;
        public static float Abs(float f) => throw null;
        public static int Abs(int value) => throw null;
        public static bool Approximately(float a, float b) => throw null;
        public static float Atan2(float y, float x) => throw null;
        public static float Ceil(float f) => throw null;
        public static int CeilToInt(float f) => throw null;
        public static float Clamp(float value, float min, float max) => throw null;
        public static int Clamp(int value, int min, int max) => throw null;
        public static float Clamp01(float value) => throw null;
        public static float Cos(float f) => throw null;
        public static float DeltaAngle(float current, float target) => throw null;
        public static float Exp(float power) => throw null;
        public static float Floor(float f) => throw null;
        public static int FloorToInt(float f) => throw null;
        public static float InverseLerp(float a, float b, float value) => throw null;
        public static float Lerp(float a, float b, float t) => throw null;
        public static float LerpUnclamped(float a, float b, float t) => throw null;
        public static float Max(float a, float b) => throw null;
        public static int Max(int a, int b) => throw null;
        public static float Min(float a, float b) => throw null;
        public static int Min(int a, int b) => throw null;
        public static float Pow(float f, float p) => throw null;
        public static float Repeat(float t, float length) => throw null;
        public static float Round(float f) => throw null;
        public static int RoundToInt(float f) => throw null;
        public static float Sin(float f) => throw null;
        public static float Sqrt(float f) => throw null;
    }
    public sealed unsafe partial class Mesh : global::UnityEngine.Object {
        private Mesh() { }
    }
    public unsafe partial class MeshRenderer : global::UnityEngine.Renderer {
        protected MeshRenderer() { }
    }
    public unsafe partial class MonoBehaviour : global::UnityEngine.Behaviour {
        public MonoBehaviour() => throw null;
        public global::UnityEngine.Coroutine StartCoroutine(global::System.Collections.IEnumerator routine) => throw null;
        public void StopCoroutine(global::UnityEngine.Coroutine routine) => throw null;
    }
    public unsafe partial class Object {
        public global::UnityEngine.HideFlags hideFlags { get => throw null; set { } }
        public string name { get => throw null; set { } }
        public static void Destroy(global::UnityEngine.Object obj) => throw null;
        public static void DestroyImmediate(global::UnityEngine.Object obj) => throw null;
        public static void DontDestroyOnLoad(global::UnityEngine.Object target) => throw null;
        public static T FindAnyObjectByType<T>() where T : global::UnityEngine.Object => throw null;
        public static T[] FindObjectsByType<T>(global::UnityEngine.FindObjectsSortMode sortMode) where T : global::UnityEngine.Object => throw null;
        public int GetInstanceID() => throw null;
        public static T Instantiate<T>(T original, global::UnityEngine.Transform parent) where T : global::UnityEngine.Object => throw null;
        public static bool operator ==(global::UnityEngine.Object x, global::UnityEngine.Object y) => throw null;
        public static implicit operator bool(global::UnityEngine.Object exists) => throw null;
        public static bool operator !=(global::UnityEngine.Object x, global::UnityEngine.Object y) => throw null;
        public override bool Equals(object obj) => throw null;
        public override int GetHashCode() => throw null;
        protected Object() { }
    }
    public unsafe partial struct Quaternion : global::System.IEquatable<global::UnityEngine.Quaternion> {
        public const float kEpsilon = 9f;
        public float w;
        public float x;
        public float y;
        public float z;
        public static global::UnityEngine.Quaternion identity { get => throw null; }
        public Quaternion(float x, float y, float z, float w) => throw null;
        public bool Equals(global::UnityEngine.Quaternion other) => throw null;
        public static global::UnityEngine.Quaternion Euler(global::UnityEngine.Vector3 euler) => throw null;
        public static global::UnityEngine.Quaternion Euler(float x, float y, float z) => throw null;
        bool global::System.IEquatable<global::UnityEngine.Quaternion>.Equals(global::UnityEngine.Quaternion other) => throw null;
    }
    public static unsafe partial class Random {
        public static int Range(int minInclusive, int maxExclusive) => throw null;
        public static float Range(float minInclusive, float maxInclusive) => throw null;
    }
    public unsafe partial struct Rect : global::System.IEquatable<global::UnityEngine.Rect> {
        private float m_Height;
        private float m_Width;
        private float m_XMin;
        private float m_YMin;
        public global::UnityEngine.Vector2 center { get => throw null; set { } }
        public float height { get => throw null; set { } }
        public global::UnityEngine.Vector2 max { get => throw null; set { } }
        public global::UnityEngine.Vector2 min { get => throw null; set { } }
        public global::UnityEngine.Vector2 size { get => throw null; set { } }
        public float width { get => throw null; set { } }
        public float x { get => throw null; set { } }
        public float xMax { get => throw null; set { } }
        public float xMin { get => throw null; set { } }
        public float y { get => throw null; set { } }
        public float yMax { get => throw null; set { } }
        public float yMin { get => throw null; set { } }
        public Rect(float x, float y, float width, float height) => throw null;
        bool global::System.IEquatable<global::UnityEngine.Rect>.Equals(global::UnityEngine.Rect other) => throw null;
    }
    public unsafe partial class RectOffset {
        public int bottom { get => throw null; set { } }
        public int left { get => throw null; set { } }
        public int right { get => throw null; set { } }
        public int top { get => throw null; set { } }
        public RectOffset() => throw null;
        public RectOffset(int left, int right, int top, int bottom) => throw null;
    }
    public sealed unsafe partial class RectTransform : global::UnityEngine.Transform {
        public global::UnityEngine.Vector2 anchorMax { get => throw null; set { } }
        public global::UnityEngine.Vector2 anchorMin { get => throw null; set { } }
        public global::UnityEngine.Vector2 anchoredPosition { get => throw null; set { } }
        public global::UnityEngine.Vector2 offsetMax { get => throw null; set { } }
        public global::UnityEngine.Vector2 offsetMin { get => throw null; set { } }
        public global::UnityEngine.Vector2 pivot { get => throw null; set { } }
        public global::UnityEngine.Rect rect { get => throw null; }
        public global::UnityEngine.Vector2 sizeDelta { get => throw null; set { } }
        public void GetWorldCorners(global::UnityEngine.Vector3[] fourCornersArray) => throw null;
        private RectTransform() { }
        public enum Edge : int {
            Left = 0,
            Right = 1,
            Top = 2,
            Bottom = 3,
        }
        public enum Axis : int {
            Horizontal = 0,
            Vertical = 1,
        }
    }
    public unsafe partial class RenderTexture : global::UnityEngine.Texture {
        public void Release() => throw null;
        protected RenderTexture() { }
    }
    public unsafe partial class Renderer : global::UnityEngine.Component {
        public bool enabled { get => throw null; set { } }
        public global::UnityEngine.Material material { get => throw null; set { } }
        public global::UnityEngine.Material sharedMaterial { get => throw null; set { } }
        public int sortingLayerID { get => throw null; set { } }
        public string sortingLayerName { get => throw null; set { } }
        public int sortingOrder { get => throw null; set { } }
        protected Renderer() { }
    }
    public sealed unsafe partial class Resources {
        public static T[] FindObjectsOfTypeAll<T>() where T : global::UnityEngine.Object => throw null;
        public static global::UnityEngine.Object[] FindObjectsOfTypeAll(global::System.Type type) => throw null;
        private Resources() { }
    }
    public enum RuntimePlatform : int {
        OSXEditor = 0,
        OSXPlayer = 1,
        WindowsPlayer = 2,
        OSXWebPlayer = 3,
        OSXDashboardPlayer = 4,
        WindowsWebPlayer = 5,
        WindowsEditor = 7,
        IPhonePlayer = 8,
        XBOX360 = 10,
        PS3 = 9,
        Android = 11,
        NaCl = 12,
        FlashPlayer = 15,
        LinuxPlayer = 13,
        LinuxEditor = 16,
        WebGLPlayer = 17,
        MetroPlayerX86 = 18,
        WSAPlayerX86 = 18,
        MetroPlayerX64 = 19,
        WSAPlayerX64 = 19,
        MetroPlayerARM = 20,
        WSAPlayerARM = 20,
        WP8Player = 21,
        BlackBerryPlayer = 22,
        TizenPlayer = 23,
        PSP2 = 24,
        PS4 = 25,
        PSM = 26,
        XboxOne = 27,
        SamsungTVPlayer = 28,
        WiiU = 30,
        tvOS = 31,
        Switch = 32,
        Lumin = 33,
        Stadia = 34,
        CloudRendering = -1,
        LinuxHeadlessSimulation = 35,
        GameCoreScarlett = -1,
        GameCoreXboxSeries = 36,
        GameCoreXboxOne = 37,
        PS5 = 38,
        EmbeddedLinuxArm64 = 39,
        EmbeddedLinuxArm32 = 40,
        EmbeddedLinuxX64 = 41,
        EmbeddedLinuxX86 = 42,
        LinuxServer = 43,
        WindowsServer = 44,
        OSXServer = 45,
        QNXArm32 = 46,
        QNXArm64 = 47,
        QNXX64 = 48,
        QNXX86 = 49,
        VisionOS = 50,
        Switch2 = 51,
        KeplerArm64 = 52,
        KeplerX64 = 53,
    }
    public sealed unsafe partial class Screen {
        public static int height { get => throw null; }
        public static int width { get => throw null; }
        private Screen() { }
    }
    public unsafe partial class ScriptableObject : global::UnityEngine.Object {
        public static T CreateInstance<T>() where T : global::UnityEngine.ScriptableObject => throw null;
        protected ScriptableObject() { }
    }
    public sealed unsafe partial class Shader : global::UnityEngine.Object {
        public static global::UnityEngine.Shader Find(string name) => throw null;
        private Shader() { }
    }
    public sealed unsafe partial class Sprite : global::UnityEngine.Object {
        public global::UnityEngine.Bounds bounds { get => throw null; }
        public global::UnityEngine.Texture2D texture { get => throw null; }
        public static global::UnityEngine.Sprite Create(global::UnityEngine.Texture2D texture, global::UnityEngine.Rect rect, global::UnityEngine.Vector2 pivot) => throw null;
        public static global::UnityEngine.Sprite Create(global::UnityEngine.Texture2D texture, global::UnityEngine.Rect rect, global::UnityEngine.Vector2 pivot, float pixelsPerUnit) => throw null;
        public static global::UnityEngine.Sprite Create(global::UnityEngine.Texture2D texture, global::UnityEngine.Rect rect, global::UnityEngine.Vector2 pivot, float pixelsPerUnit, uint extrude, global::UnityEngine.SpriteMeshType meshType, global::UnityEngine.Vector4 border) => throw null;
        private Sprite() { }
    }
    public enum SpriteMeshType : int {
        FullRect = 0,
        Tight = 1,
    }
    public sealed unsafe partial class SpriteRenderer : global::UnityEngine.Renderer {
        public global::UnityEngine.Color color { get => throw null; set { } }
        public global::UnityEngine.Sprite sprite { get => throw null; set { } }
        private SpriteRenderer() { }
    }
    public enum SystemLanguage : int {
        Afrikaans = 0,
        Arabic = 1,
        Basque = 2,
        Belarusian = 3,
        Bulgarian = 4,
        Catalan = 5,
        Chinese = 6,
        Czech = 7,
        Danish = 8,
        Dutch = 9,
        English = 10,
        Estonian = 11,
        Faroese = 12,
        Finnish = 13,
        French = 14,
        German = 15,
        Greek = 16,
        Hebrew = 17,
        Icelandic = 19,
        Indonesian = 20,
        Italian = 21,
        Japanese = 22,
        Korean = 23,
        Latvian = 24,
        Lithuanian = 25,
        Norwegian = 26,
        Polish = 27,
        Portuguese = 28,
        Romanian = 29,
        Russian = 30,
        SerboCroatian = 31,
        Slovak = 32,
        Slovenian = 33,
        Spanish = 34,
        Swedish = 35,
        Thai = 36,
        Turkish = 37,
        Ukrainian = 38,
        Vietnamese = 39,
        ChineseSimplified = 40,
        ChineseTraditional = 41,
        Hindi = 42,
        Unknown = 43,
        Hungarian = 18,
    }
    public unsafe partial class Texture : global::UnityEngine.Object {
        public int anisoLevel { get => throw null; set { } }
        public global::UnityEngine.FilterMode filterMode { get => throw null; set { } }
        public virtual int height { get => throw null; set { } }
        public virtual bool isReadable { get => throw null; }
        public float mipMapBias { get => throw null; set { } }
        public virtual int width { get => throw null; set { } }
        public global::UnityEngine.TextureWrapMode wrapMode { get => throw null; set { } }
        protected Texture() { }
    }
    public sealed unsafe partial class Texture2D : global::UnityEngine.Texture {
        public Texture2D(int width, int height, global::UnityEngine.TextureFormat textureFormat, bool mipChain) => throw null;
        public Texture2D(int width, int height, global::UnityEngine.TextureFormat textureFormat, bool mipChain, bool linear) => throw null;
        public void Apply() => throw null;
        public void Apply(bool updateMipmaps) => throw null;
        public void Apply(bool updateMipmaps, bool makeNoLongerReadable) => throw null;
        public void Compress(bool highQuality) => throw null;
        public global::UnityEngine.Color32[] GetPixels32() => throw null;
        public void LoadRawTextureData(byte[] data) => throw null;
        public global::UnityEngine.Rect[] PackTextures(global::UnityEngine.Texture2D[] textures, int padding, int maximumAtlasSize, bool makeNoLongerReadable) => throw null;
        public void SetPixel(int x, int y, global::UnityEngine.Color color) => throw null;
        public void SetPixels(global::UnityEngine.Color[] colors) => throw null;
        public void SetPixels32(global::UnityEngine.Color32[] colors) => throw null;
        private Texture2D() { }
        public enum EXRFlags : int {
            None = 0,
            OutputAsFloat = 1,
            CompressZIP = 2,
            CompressRLE = 4,
            CompressPIZ = 8,
        }
    }
    public enum TextureFormat : int {
        Alpha8 = 1,
        ARGB4444 = 2,
        RGB24 = 3,
        RGBA32 = 4,
        ARGB32 = 5,
        RGB565 = 7,
        R16 = 9,
        DXT1 = 10,
        DXT5 = 12,
        RGBA4444 = 13,
        BGRA32 = 14,
        RHalf = 15,
        RGHalf = 16,
        RGBAHalf = 17,
        RFloat = 18,
        RGFloat = 19,
        RGBAFloat = 20,
        YUY2 = 21,
        RGB9e5Float = 22,
        BC4 = 26,
        BC5 = 27,
        BC6H = 24,
        BC7 = 25,
        DXT1Crunched = 28,
        DXT5Crunched = 29,
        PVRTC_RGB2 = 30,
        PVRTC_RGBA2 = 31,
        PVRTC_RGB4 = 32,
        PVRTC_RGBA4 = 33,
        ETC_RGB4 = 34,
        EAC_R = 41,
        EAC_R_SIGNED = 42,
        EAC_RG = 43,
        EAC_RG_SIGNED = 44,
        ETC2_RGB = 45,
        ETC2_RGBA1 = 46,
        ETC2_RGBA8 = 47,
        ASTC_4x4 = 48,
        ASTC_5x5 = 49,
        ASTC_6x6 = 50,
        ASTC_8x8 = 51,
        ASTC_10x10 = 52,
        ASTC_12x12 = 53,
        RG16 = 62,
        R8 = 63,
        ETC_RGB4Crunched = 64,
        ETC2_RGBA8Crunched = 65,
        ASTC_HDR_4x4 = 66,
        ASTC_HDR_5x5 = 67,
        ASTC_HDR_6x6 = 68,
        ASTC_HDR_8x8 = 69,
        ASTC_HDR_10x10 = 70,
        ASTC_HDR_12x12 = 71,
        RG32 = 72,
        RGB48 = 73,
        RGBA64 = 74,
        R8_SIGNED = 75,
        RG16_SIGNED = 76,
        RGB24_SIGNED = 77,
        RGBA32_SIGNED = 78,
        R16_SIGNED = 79,
        RG32_SIGNED = 80,
        RGB48_SIGNED = 81,
        RGBA64_SIGNED = 82,
    }
    public enum TextureWrapMode : int {
        Repeat = 0,
        Clamp = 1,
        Mirror = 2,
        MirrorOnce = 3,
    }
    public unsafe partial class Time {
        public static int frameCount { get => throw null; }
        public static float realtimeSinceStartup { get => throw null; }
        public static double realtimeSinceStartupAsDouble { get => throw null; }
        public static float time { get => throw null; }
        public static float timeScale { get => throw null; set { } }
        public static float unscaledDeltaTime { get => throw null; }
        public static float unscaledTime { get => throw null; }
        public static double unscaledTimeAsDouble { get => throw null; }
        protected Time() { }
    }
    public unsafe partial class Transform : global::UnityEngine.Component, global::System.Collections.IEnumerable {
        public int childCount { get => throw null; }
        public global::UnityEngine.Vector3 localEulerAngles { get => throw null; set { } }
        public global::UnityEngine.Vector3 localPosition { get => throw null; set { } }
        public global::UnityEngine.Quaternion localRotation { get => throw null; set { } }
        public global::UnityEngine.Vector3 localScale { get => throw null; set { } }
        public global::UnityEngine.Vector3 lossyScale { get => throw null; }
        public global::UnityEngine.Transform parent { get => throw null; set { } }
        public global::UnityEngine.Vector3 position { get => throw null; set { } }
        public global::UnityEngine.Quaternion rotation { get => throw null; set { } }
        public global::UnityEngine.Transform Find(string n) => throw null;
        public global::UnityEngine.Transform GetChild(int index) => throw null;
        public virtual global::System.Collections.IEnumerator GetEnumerator() => throw null;
        public int GetSiblingIndex() => throw null;
        public global::UnityEngine.Vector3 InverseTransformPoint(global::UnityEngine.Vector3 position) => throw null;
        public bool IsChildOf(global::UnityEngine.Transform parent) => throw null;
        public void SetAsFirstSibling() => throw null;
        public void SetAsLastSibling() => throw null;
        public void SetParent(global::UnityEngine.Transform parent, bool worldPositionStays) => throw null;
        public void SetSiblingIndex(int index) => throw null;
        public global::UnityEngine.Vector3 TransformPoint(global::UnityEngine.Vector3 position) => throw null;
        protected Transform() { }
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => throw null;
    }
    public unsafe partial struct Vector2 : global::System.IEquatable<global::UnityEngine.Vector2> {
        public const float kEpsilon = 10f;
        public const float kEpsilonNormalSqrt = 11f;
        public float x;
        public float y;
        public float magnitude { get => throw null; }
        public static global::UnityEngine.Vector2 one { get => throw null; }
        public float sqrMagnitude { get => throw null; }
        public static global::UnityEngine.Vector2 zero { get => throw null; }
        public Vector2(float x, float y) => throw null;
        public static float Dot(global::UnityEngine.Vector2 lhs, global::UnityEngine.Vector2 rhs) => throw null;
        public static global::UnityEngine.Vector2 LerpUnclamped(global::UnityEngine.Vector2 a, global::UnityEngine.Vector2 b, float t) => throw null;
        public static global::UnityEngine.Vector2 Max(global::UnityEngine.Vector2 lhs, global::UnityEngine.Vector2 rhs) => throw null;
        public static global::UnityEngine.Vector2 Min(global::UnityEngine.Vector2 lhs, global::UnityEngine.Vector2 rhs) => throw null;
        public static global::UnityEngine.Vector2 SmoothDamp(global::UnityEngine.Vector2 current, global::UnityEngine.Vector2 target, ref global::UnityEngine.Vector2 currentVelocity, float smoothTime) => throw null;
        public static global::UnityEngine.Vector2 operator +(global::UnityEngine.Vector2 a, global::UnityEngine.Vector2 b) => throw null;
        public static global::UnityEngine.Vector2 operator /(global::UnityEngine.Vector2 a, float d) => throw null;
        public static bool operator ==(global::UnityEngine.Vector2 lhs, global::UnityEngine.Vector2 rhs) => throw null;
        public static implicit operator global::UnityEngine.Vector2(global::UnityEngine.Vector3 v) => throw null;
        public static implicit operator global::UnityEngine.Vector3(global::UnityEngine.Vector2 v) => throw null;
        public static bool operator !=(global::UnityEngine.Vector2 lhs, global::UnityEngine.Vector2 rhs) => throw null;
        public static global::UnityEngine.Vector2 operator *(global::UnityEngine.Vector2 a, float d) => throw null;
        public static global::UnityEngine.Vector2 operator *(global::UnityEngine.Vector2 a, global::UnityEngine.Vector2 b) => throw null;
        public static global::UnityEngine.Vector2 operator -(global::UnityEngine.Vector2 a, global::UnityEngine.Vector2 b) => throw null;
        public override bool Equals(object obj) => throw null;
        public override int GetHashCode() => throw null;
        bool global::System.IEquatable<global::UnityEngine.Vector2>.Equals(global::UnityEngine.Vector2 other) => throw null;
    }
    public unsafe partial struct Vector2Int : global::System.IEquatable<global::UnityEngine.Vector2Int> {
        private int m_X;
        private int m_Y;
        public int x { get => throw null; set { } }
        public int y { get => throw null; set { } }
        public Vector2Int(int x, int y) => throw null;
        bool global::System.IEquatable<global::UnityEngine.Vector2Int>.Equals(global::UnityEngine.Vector2Int other) => throw null;
    }
    public unsafe partial struct Vector3 : global::System.IEquatable<global::UnityEngine.Vector3> {
        public const float kEpsilon = 12f;
        public const float kEpsilonNormalSqrt = 13f;
        public float x;
        public float y;
        public float z;
        public static global::UnityEngine.Vector3 one { get => throw null; }
        public static global::UnityEngine.Vector3 zero { get => throw null; }
        public Vector3(float x, float y) => throw null;
        public Vector3(float x, float y, float z) => throw null;
        public static float Distance(global::UnityEngine.Vector3 a, global::UnityEngine.Vector3 b) => throw null;
        public static global::UnityEngine.Vector3 LerpUnclamped(global::UnityEngine.Vector3 a, global::UnityEngine.Vector3 b, float t) => throw null;
        public static global::UnityEngine.Vector3 operator +(global::UnityEngine.Vector3 a, global::UnityEngine.Vector3 b) => throw null;
        public static bool operator ==(global::UnityEngine.Vector3 lhs, global::UnityEngine.Vector3 rhs) => throw null;
        public static bool operator !=(global::UnityEngine.Vector3 lhs, global::UnityEngine.Vector3 rhs) => throw null;
        public static global::UnityEngine.Vector3 operator *(global::UnityEngine.Vector3 a, float d) => throw null;
        public override bool Equals(object obj) => throw null;
        public override int GetHashCode() => throw null;
        bool global::System.IEquatable<global::UnityEngine.Vector3>.Equals(global::UnityEngine.Vector3 other) => throw null;
    }
    public unsafe partial struct Vector4 : global::System.IEquatable<global::UnityEngine.Vector4> {
        public const float kEpsilon = 14f;
        public float w;
        public float x;
        public float y;
        public float z;
        public Vector4(float x, float y, float z, float w) => throw null;
        public static bool operator ==(global::UnityEngine.Vector4 lhs, global::UnityEngine.Vector4 rhs) => throw null;
        public static implicit operator global::UnityEngine.Vector4(global::UnityEngine.Vector2 v) => throw null;
        public static bool operator !=(global::UnityEngine.Vector4 lhs, global::UnityEngine.Vector4 rhs) => throw null;
        public override bool Equals(object obj) => throw null;
        public override int GetHashCode() => throw null;
        bool global::System.IEquatable<global::UnityEngine.Vector4>.Equals(global::UnityEngine.Vector4 other) => throw null;
    }
    public sealed unsafe partial class WaitForEndOfFrame : global::UnityEngine.YieldInstruction {
        public WaitForEndOfFrame() => throw null;
    }
    public unsafe partial class YieldInstruction {
        protected YieldInstruction() { }
    }
}
namespace UnityEngine.Events {
    public unsafe delegate void UnityAction();
    public unsafe delegate void UnityAction<T0>(T0 arg0);
    public unsafe delegate void UnityAction<T0, T1>(T0 arg0, T1 arg1);
    public unsafe partial class UnityEvent : global::UnityEngine.Events.UnityEventBase {
        public void AddListener(global::UnityEngine.Events.UnityAction call) => throw null;
        protected UnityEvent() { }
    }
    public abstract unsafe partial class UnityEventBase {
        public void RemoveAllListeners() => throw null;
        protected UnityEventBase() { }
    }
    public unsafe partial class UnityEvent<T0> : global::UnityEngine.Events.UnityEventBase {
        public void AddListener(global::UnityEngine.Events.UnityAction<T0> call) => throw null;
        protected UnityEvent() { }
    }
}
namespace UnityEngine.Internal {
    public unsafe partial interface ISubAssetNotDuplicatable {
    }
}
namespace UnityEngine.SceneManagement {
    public enum LoadSceneMode : int {
        Single = 0,
        Additive = 1,
    }
    public unsafe partial struct Scene {
        private global::UnityEngine.SceneManagement.SceneHandle m_Handle;
        public string name { get => throw null; set { } }
        public global::UnityEngine.GameObject[] GetRootGameObjects() => throw null;
    }
    public unsafe partial struct SceneHandle : global::System.IEquatable<global::UnityEngine.SceneManagement.SceneHandle> {
        private global::UnityEngine.EntityId m_Value;
        bool global::System.IEquatable<global::UnityEngine.SceneManagement.SceneHandle>.Equals(global::UnityEngine.SceneManagement.SceneHandle other) => throw null;
    }
    public unsafe partial class SceneManager {
        public static event global::UnityEngine.Events.UnityAction<global::UnityEngine.SceneManagement.Scene, global::UnityEngine.SceneManagement.LoadSceneMode> sceneLoaded { add { } remove { } }
        public static event global::UnityEngine.Events.UnityAction<global::UnityEngine.SceneManagement.Scene> sceneUnloaded { add { } remove { } }
        public static global::UnityEngine.SceneManagement.Scene GetActiveScene() => throw null;
        public static void LoadScene(string sceneName) => throw null;
        protected SceneManager() { }
    }
}
namespace UnityEngine.Scripting {
    public static unsafe partial class GarbageCollector {
        public static bool isIncremental { get => throw null; }
        public enum Mode : int {
            Disabled = 0,
            Enabled = 1,
            Manual = 2,
        }
    }
}
