// <auto-generated>
//   Compile-only stand-in for "Assembly-CSharp", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

public unsafe partial class ADOBase : global::RDTools.RDBaseDll {
    public static global::scrConductor conductor { get => throw null; }
    public static global::scrController controller { get => throw null; }
    public static string currentLevel { get => throw null; }
    public static global::scnGame customLevel { get => throw null; }
    public static global::scnEditor editor { get => throw null; }
    public static global::RDConstants gc { get => throw null; }
    public static bool isLevelEditor { get => throw null; }
    public static bool isLevelSelect { get => throw null; }
    public static bool isOfficialLevel { get => throw null; }
    public static bool isSwitch { get => throw null; }
    public static string levelPath { get => throw null; }
    public static global::scnLevelSelect levelSelect { get => throw null; }
    public static global::scrLevelMaker lm { get => throw null; }
    public static global::scrPlayerManager playerManager { get => throw null; }
    public bool practiceAvailable { get => throw null; }
    protected ADOBase() { }
}
public unsafe partial class ADOClass : global::RDTools.RDClassDll {
    protected ADOClass() { }
}
public unsafe partial struct AnyKeyCode {
    public readonly global::System.Func<object, object, bool> equalsCriteria;
    public readonly object value;
    public readonly global::System.Type valueType;
}
public unsafe partial class AsyncInputManager : global::UnityEngine.MonoBehaviour {
    public static bool isActive { get => throw null; }
    protected AsyncInputManager() { }
}
public unsafe partial struct AsyncKeyCode {
    public readonly ushort key;
    public readonly global::SkyHook.KeyLabel label;
}
public unsafe partial class AudioManager : global::ADOBase {
    public static global::AudioManager Instance { get => throw null; }
    public global::UnityEngine.AudioClip FindOrLoadAudioClip(string clipName, string internalLevelName = default, bool fromBundle = default) => throw null;
    public static global::UnityEngine.AudioSource Play(string snd, double time, global::UnityEngine.Audio.AudioMixerGroup group, float volume = default, int priority = default) => throw null;
    public void StopAllSounds() => throw null;
    protected AudioManager() { }
}
public enum BGShapeType : int {
    Default = 0,
    SingleColor = 1,
    Disabled = 2,
}
public enum ButtonState : int {
    WentDown = 0,
    WentUp = 1,
    IsDown = 2,
    IsUp = 3,
}
public unsafe partial struct CalibrationPreset {
    public const int DontModifyVisualOffset = 0;
    public bool confident;
    public int inputOffset;
    public string outputName;
    public global::AudioOutputType outputType;
    public int priority;
}
public abstract unsafe partial class DLCManager {
    public static global::System.Collections.Generic.HashSet<global::DLCManager> DLCManagers;
    public string groupName;
    public bool installed;
    public uint steamAppId;
    public bool upToDate;
    public virtual bool IsDLCLevel(string name) => throw null;
    protected DLCManager() { }
}
public enum DecPlacementType : int {
    Tile = 0,
    Global = 1,
    RedPlanet = 2,
    BluePlanet = 3,
    GreenPlanet = 4,
    Camera = 5,
    CameraAspect = 6,
    LastPosition = 7,
}
public unsafe partial class DecorationsArray<T> : global::System.Collections.Generic.List<T> {
    protected DecorationsArray() { }
}
public enum Difficulty : int {
    Lenient = 0,
    Normal = 1,
    Strict = 2,
}
public unsafe partial class DiscordController : global::ADOBase {
    public static bool shouldUpdatePresence;
    protected DiscordController() { }
}
public unsafe partial class EditorDifficultySelector : global::ADOBase {
    protected EditorDifficultySelector() { }
}
public enum ErrorMeterSize : int {
    Off = 0,
    Small = 1,
    Normal = 2,
    Large = 3,
    ExtraLarge = 4,
}
public unsafe partial class EventsArray<T> : global::System.Collections.Generic.List<T> {
    protected EventsArray() { }
}
public static unsafe partial class ExtensionMethods {
    public static global::UnityEngine.Color WithAlpha(this global::UnityEngine.Color color, float alpha) => throw null;
}
public enum FloorIcon : int {
    None = 0,
    Snail = 1,
    DoubleSnail = 2,
    Rabbit = 3,
    DoubleRabbit = 4,
    Swirl = 5,
    SwirlCW = 6,
    SameSpeed = 7,
    OneVfx = 8,
    Vfx = 9,
    Checkpoint = 10,
    HoldArrowShort = 11,
    HoldArrowLong = 12,
    HoldReleaseShort = 13,
    HoldReleaseLong = 14,
    MultiPlanetTwo = 15,
    MultiPlanetThreeMore = 16,
    MultiPlanetThreeLess = 17,
    ForceNone = 18,
    AnimatedSnail = 19,
    AnimatedRabbit = 20,
    AnimatedDoubleSnail = 21,
    AnimatedDoubleRabbit = 22,
    Decoration = 23,
    Portal = 24,
}
public unsafe partial class FloorMesh : global::UnityEngine.MonoBehaviour {
    public static global::System.Collections.Generic.Dictionary<string, global::FloorMesh.MeshCache> cache;
    protected FloorMesh() { }
    public unsafe partial class MeshCache {
        protected MeshCache() { }
    }
}
public abstract unsafe partial class FloorRenderer : global::ADOBase {
    public global::UnityEngine.Color cachedColor;
    public global::UnityEngine.Color deselectedColor;
    public global::UnityEngine.Renderer renderer;
    public virtual global::UnityEngine.Color color { get => throw null; set { } }
    protected FloorRenderer() { }
}
public unsafe partial class FloorSpriteRenderer : global::FloorRenderer {
    protected FloorSpriteRenderer() { }
}
public unsafe partial class GCS {
    public const float ALLOWED_KEYS_RESET_TIME = 1f;
    public const string AVIFileExtension = "AVIFileExtension";
    public const string AifFileExtension = "AifFileExtension";
    public const string AiffFileExtension = "AiffFileExtension";
    public const string ExternalSoundSuffix = "ExternalSoundSuffix";
    public const string FLVFileExtension = "FLVFileExtension";
    public const string GIFFileExtension = "GIFFileExtension";
    public const float HITMARGIN_ABSOLUTE_MINIMUM_SECONDS = 8f;
    public const float HITMARGIN_MINIMUM_SECONDS_EASY = 9f;
    public const float HITMARGIN_MINIMUM_SECONDS_HARD = 10f;
    public const float HITMARGIN_MINIMUM_SECONDS_MOBILE = 11f;
    public const float HITMARGIN_MINIMUM_SECONDS_NORMAL = 12f;
    public const float HITMARGIN_PERFECT = 13f;
    public const float HITMARGIN_PERFECT_MINIMUM_SECONDS = 14f;
    public const float HITMARGIN_PERFECT_MINIMUM_SECONDS_MOBILE = 15f;
    public const float HITMARGIN_PURE = 16f;
    public const float HITMARGIN_PURE_MINIMUM_SECONDS = 17f;
    public const float HITMARGIN_PURE_MINIMUM_SECONDS_MOBILE = 18f;
    public const string JPEGFileExtension = "JPEGFileExtension";
    public const string JPGFileExtension = "JPGFileExtension";
    public const int LargeFloorSize = 21;
    public const float LenientOptionMinimumBPM_Custom = 22f;
    public const int MAXIMUM_ALLOWED_KEYS = 23;
    public const int MAXIMUM_UNLOCKED_ALLOWED_KEYS = 24;
    public const int MINIMUM_USED_KEYS_RESULT = 25;
    public const string MOVFileExtension = "MOVFileExtension";
    public const string MP3FileExtension = "MP3FileExtension";
    public const string MP4FileExtension = "MP4FileExtension";
    public const string OggVorbisFileExtension = "OggVorbisFileExtension";
    public const string PNGFileExtension = "PNGFileExtension";
    public const bool RandomValuesEnabled = false;
    public const float StrictOptionMinimumBPM_Custom = 32f;
    public const string WEBMFileExtension = "WEBMFileExtension";
    public const string WMVFileExtension = "WMVFileExtension";
    public const string WavFileExtension = "WavFileExtension";
    public static int customLevelIndex;
    public static string[] customLevelPaths;
    public static global::Difficulty difficulty;
    public const float frameTimeSensitivity = 36f;
    public const float framesPerTileLimit = 37f;
    public static string internalLevelName;
    public const string jsonExtension = "jsonExtension";
    public static global::System.Collections.Generic.Dictionary<string, global::ADOFAI.LevelEventInfo> levelEventsInfo;
    public const string levelExtension = "levelExtension";
    public const string levelZipExtension = "levelZipExtension";
    public const float minSpeedrunSpeed = 41f;
    public const float msPerTileConsecLimit = 42f;
    public const float msPerTileLimit = 43f;
    public const float multiplierIncrement = 44f;
    public const int multipressOverload = 45;
    public static float nextSpeedRun;
    public static bool playDeathSound;
    public static bool practiceMode;
    public static string sceneToLoad;
    public const float semitone = 46f;
    public static global::System.Collections.Generic.Dictionary<string, global::ADOFAI.LevelEventInfo> settingsInfo;
    public static bool speedTrialMode;
    public static string steamBranchName;
    public static bool useNoFail;
    public const bool usingCheckpoints = false;
    public static bool webVersion;
    public static string worldEntrance;
    public const string zipExtension = "zipExtension";
    public static int checkpointNum { get => throw null; set { } }
    protected GCS() { }
}
public static unsafe partial class GOExtensions {
    public static T GetOrAddComponent<T>(this global::UnityEngine.GameObject gameObject) where T : global::UnityEngine.Component => throw null;
}
public abstract unsafe partial class GeneralPauseButton : global::ADOBase {
    protected GeneralPauseButton() { }
}
public enum HitMargin : int {
    TooEarly = 0,
    VeryEarly = 1,
    EarlyPerfect = 2,
    Perfect = 3,
    LatePerfect = 4,
    VeryLate = 5,
    TooLate = 6,
    Multipress = 7,
    FailMiss = 8,
    FailOverload = 9,
    Auto = 10,
    OverPress = 11,
}
public enum HitboxType : int {
    None = 0,
    Kill = 1,
    Event = 2,
}
public enum HoldBehavior : int {
    Normal = 0,
    CanHitEnd = 1,
    NoHoldNeeded = 2,
}
public enum InputAction : int {
    Main = 0,
    Skip = 1,
    Cancel = 2,
    Quit = 3,
    Restart = 4,
    Left = 5,
    Right = 6,
    Up = 7,
    Down = 8,
    LeftAlt = 9,
    RightAlt = 10,
    UpAlt = 11,
    DownAlt = 12,
    Action1 = 13,
    Action2 = 14,
    Confirm = 15,
    Back = 16,
    FaceUp = 17,
    FaceLeft = 18,
}
public abstract unsafe partial class LevelSelectBase : global::ADOBase {
    protected LevelSelectBase() { }
}
public unsafe partial class NewsSign : global::ADOBase {
    public global::scrButtonURL button;
    protected NewsSign() { }
}
public enum ObjectDecorationType : int {
    Floor = 0,
    Planet = 1,
    PlayerBubble = 2,
}
public unsafe partial class PauseMenu : global::ADOBase {
    public const float pauseButtonWidth = 49f;
    public void PlayMenuSfx(global::SfxSound sound, float volume = default) => throw null;
    protected PauseMenu() { }
    public enum ButtonType : int {
        Continue = 0,
        LevelEditor = 1,
        SteamWorkshop = 2,
        Refresh = 3,
        Practice = 4,
        Settings = 5,
        Calibration = 6,
        Discord = 7,
        QQ = 8,
        GameCenter = 9,
        PlayGames = 10,
        Quit = 11,
        LoadLevel = 12,
        ChangePlayers = 13,
    }
    public enum Submenu : int {
        Main = 0,
        Settings = 1,
        PlayerSelect = 2,
    }
}
public unsafe partial class PauseSettingButton : global::GeneralPauseButton {
    public object CachedValue;
    public object initialValue;
    public string unit;
    public global::UnityEngine.UI.Text valueLabel;
    public void PlayArrowAnimation(bool isRight) => throw null;
    protected PauseSettingButton() { }
}
public unsafe partial class Persistence : global::RDTools.RDClassDll {
    public const float inputOffsetNotSet = 50f;
    public static global::ErrorMeterSize hitErrorMeterSize { get => throw null; set { } }
    public static global::HoldBehavior holdBehavior { get => throw null; set { } }
    public static bool GetHideCursorWhilePlaying() => throw null;
    public static void WriteSaveToDisk() => throw null;
    protected Persistence() { }
}
public unsafe partial class PlanetRenderer : global::ADOBase {
    public global::UnityEngine.ParticleSystem coreParticles;
    public global::UnityEngine.SpriteRenderer faceDetails;
    public global::UnityEngine.SpriteRenderer faceSprite;
    public global::UnityEngine.SpriteRenderer glow;
    public global::scrRing ringComp;
    public global::UnityEngine.SpriteRenderer samuraiSprite;
    public global::UnityEngine.ParticleSystem sparks;
    public global::PlanetSprite sprite;
    public global::UnityEngine.ParticleSystem tailParticles;
    public void DisableAllSpecialPlanets() => throw null;
    public void LoadPlanetColor(bool isRed) => throw null;
    public void PlayParticles() => throw null;
    public void Revive(bool liteRevive = default) => throw null;
    public void SetCoreColor(global::UnityEngine.Color color) => throw null;
    public void SetPlanetColor(global::UnityEngine.Color color) => throw null;
    public void SetTailColor(global::UnityEngine.Color color) => throw null;
    protected PlanetRenderer() { }
}
public unsafe partial class PlanetSprite : global::ADOBase {
    public global::UnityEngine.SpriteRenderer meshRenderer;
    public global::UnityEngine.Texture sprite { get => throw null; set { } }
    protected PlanetSprite() { }
}
public unsafe partial class PlanetarySystem : global::ADOBase {
    public global::System.Collections.Generic.List<global::scrPlanet> allPlanets;
    public global::scrPlanet chosenPlanet;
    public bool isCW;
    public global::scrPlanet planetBlue;
    public global::System.Collections.Generic.List<global::scrPlanet> planetList;
    public global::scrPlanet planetRed;
    public double speed;
    protected PlanetarySystem() { }
    public enum DeathAnimation : int {
        Explode = 0,
        CrumbleAndExplode = 1,
        Crumble = 2,
    }
}
public enum Portal : int {
    None = 0,
    EndOfLevel = 1,
    LastLevelPlayed = 2,
    CalibrationScene = 3,
    EditorScene = 4,
    CustomLevelsScene = 5,
    RDSteamPage = 6,
    PreviousLevel = 7,
    NextLevel = 8,
    LowerSpeed = 9,
    HigherSpeed = 10,
    GoToLevel = 11,
    GoToLevelSpeedTrial = 12,
    GoToWorldBossIfReached = 13,
    TaroDLCMapExit = 14,
    TaroDLCMap = 15,
    PuzzleTest = 16,
    Puzzle1 = 17,
    Puzzle2 = 18,
    Puzzle3 = 19,
    TaroDLCMap3 = 20,
    VegaDLCMap = 21,
    FoolJoker = 22,
}
public unsafe partial class PostEffectsBase : global::UnityEngine.MonoBehaviour {
    protected PostEffectsBase() { }
}
public unsafe partial class PracticeTimeline : global::ADOBase {
    public global::UnityEngine.UI.RawImage waveRaw;
    public void Init() => throw null;
    protected PracticeTimeline() { }
}
public unsafe partial class RDC {
    public static bool auto { get => throw null; set { } }
    public static bool debug { get => throw null; set { } }
    public static bool noHud { get => throw null; set { } }
    public static bool runningOnSteamDeck { get => throw null; set { } }
    public static bool useOldAuto { get => throw null; set { } }
    protected RDC() { }
}
public unsafe partial class RDConstants : global::UnityEngine.ScriptableObject {
    public global::UnityEngine.GameObject prefab_property;
    public global::UnityEngine.Texture2D tex_planetWhite;
    protected RDConstants() { }
}
public static unsafe partial class RDEditorUtils {
    public static bool CheckModsDependency(object[] mods) => throw null;
}
public static unsafe partial class RDExtensions {
    public static void SetAlpha(this global::UnityEngine.SpriteRenderer sr, float alpha) => throw null;
}
public abstract unsafe partial class RDFile {
    public static bool Exists(string path) => throw null;
    public static byte[] ReadAllBytes(string path, out global::ADOFAI.LoadResult loadResult) => throw null;
    protected RDFile() { }
}
public static unsafe partial class RDInput {
    public static bool holdingControl { get => throw null; }
    public static bool holdingShift { get => throw null; }
    public static global::UnityEngine.Vector2 mouseScrollDelta { get => throw null; }
    public static int GetMain(global::ButtonState state = default) => throw null;
    public static global::System.Collections.Generic.List<global::AnyKeyCode> GetMainPressKeys() => throw null;
    public static bool GetState(global::InputAction inputAction, global::ButtonState state = default) => throw null;
    public static global::System.Collections.Generic.List<global::AnyKeyCode> GetStateKeys(global::ButtonState state = default) => throw null;
    public static bool IsDown(this global::UnityEngine.KeyCode key) => throw null;
    public static bool WentDown(this global::UnityEngine.KeyCode key) => throw null;
    public static bool WentUp(this global::UnityEngine.KeyCode key) => throw null;
}
public abstract unsafe partial class RDInputType {
    protected RDInputType() { }
}
public static unsafe partial class RDString {
    public const string BoothButtonKeySuffix = "BoothButtonKeySuffix";
    public const string DivekickKeySuffix = "DivekickKeySuffix";
    public const global::UnityEngine.SystemLanguage FallbackLanguage = (global::UnityEngine.SystemLanguage)(53);
    public const string GamepadKeySuffix = "GamepadKeySuffix";
    public const string MobileKeySuffix = "MobileKeySuffix";
    public const string NintendoSwitchFaceRightCharacter = "NintendoSwitchFaceRightCharacter";
    public const string NintendoSwitchKeySuffix = "NintendoSwitchKeySuffix";
    public const string StringsFilePrefix = "StringsFilePrefix";
    public const string StringsFolder = "StringsFolder";
    public static string GetWithCheck(string key, out bool exists, global::System.Collections.Generic.Dictionary<string, object> parameters = default) => throw null;
    public static void SetLocalizedFont(this global::UnityEngine.UI.Text text) => throw null;
    public static void SetLocalizedFont(this global::TMPro.TMP_Text text) => throw null;
    public static void SetLocalizedFont(this global::UnityEngine.TextMesh text) => throw null;
}
public unsafe partial class SaveStateScope : global::System.IDisposable {
    public SaveStateScope(global::scnEditor editor, bool clearRedo = default, bool dataHasChanged = default, bool skipSaving = default) => throw null;
    protected SaveStateScope() { }
    void global::System.IDisposable.Dispose() => throw null;
}
public unsafe partial class ScreenScroll : global::UnityEngine.MonoBehaviour {
    public global::UnityEngine.Vector2 scrollOffset;
    public global::UnityEngine.Vector2 scrollSpeed;
    protected ScreenScroll() { }
}
public unsafe partial class ScreenTile : global::UnityEngine.MonoBehaviour {
    public float tileX;
    public float tileY;
    protected ScreenTile() { }
}
public unsafe partial class SettingsMenu : global::ADOBase {
    public void Show() => throw null;
    public void UpdateSetting(global::PauseSettingButton setting, global::SettingsMenu.Interaction action) => throw null;
    protected SettingsMenu() { }
    public enum Interaction : int {
        Refresh = 0,
        Activate = 1,
        ActivateInfo = 2,
        Increment = 3,
        Decrement = 4,
    }
}
public enum SfxSound : int {
    PowerUp = 0,
    PowerDown = 1,
    MenuSquelch = 2,
    ApplauseQuiet = 3,
    Applause = 4,
    OttoActivate = 5,
    OttoActivateNervous = 6,
    OttoDeactivate = 7,
    OttoHappy = 8,
    Wilhelm = 9,
    ModifierActivate = 10,
    ModifierDeactivate = 11,
    ScreenWipeIn = 12,
    ScreenWipeOut = 13,
    PurePerfect = 14,
    MenuCrack = 15,
    SpeechOverseer = 16,
    SpeechCharlie = 17,
    SpeechSef = 18,
    MawaruCoin = 19,
    MawaruLaser = 20,
    MawaruWrong = 21,
    Banish = 22,
    PlanetTransform = 23,
    MenuCrackFinal = 24,
    EnterNeoCosmos = 25,
    MobileButton = 26,
    MobileButtonLeft = 27,
    MobileButtonRight = 28,
    MobileButtonEnter = 29,
    PortalSelect = 30,
    PortalDeselect = 31,
    PortalLocked = 32,
    PlanetCatch = 33,
    PlanetRelease = 34,
    PlanetPaint = 35,
    SpeedTrialOn = 36,
    SpeedTrialOff = 37,
    NotificationIn = 38,
    NotificationOut = 39,
    MobileMenuXC1 = 40,
    MobileMenuXC2 = 41,
    MobileMenuXC3 = 42,
    MobileMenuXF = 43,
    MobileMenuXR1 = 44,
    MobileMenuXR2 = 45,
    MobileMenuXR3 = 46,
    MobileMenuXH = 47,
    MobileMenuMineswooce = 48,
    MenuStonePanelOpen = 49,
    MenuStonePanelClose = 50,
    FireTile = 51,
    IceTile = 52,
    YouFool = 53,
    YouAbsoluteBuffoon = 54,
    PlanetPreExplosion = 55,
    PlanetExplosion = 56,
    PlanetExplosionHighscore = 57,
    Calibration = 58,
    AchievementBubbleOpen = 59,
    AchievementBubbleClose = 60,
    AchievementIconBurst = 61,
    AchievementJingle = 62,
    AchievementJingleSmall = 63,
    PlanetPreExplosionCoop = 64,
    PlanetExplosionCoop = 65,
    PlanetBubblePop = 66,
    PlanetRevive = 67,
    NotificationTinyText = 68,
    MenuPause = 69,
    MenuUnpause = 70,
    MenuNavigate = 71,
    MenuBack = 72,
    MenuIncrement = 73,
    MenuDecrement = 74,
    MenuGoatProjector = 75,
    MenuChainSlideIn = 76,
    MenuChainSlideOut = 77,
}
public enum States : int {
    None = 0,
    Start = 1,
    Countdown = 2,
    Checkpoint = 3,
    PlayerControl = 4,
    Fail = 5,
    Fail2 = 6,
    Won = 7,
}
public unsafe partial class TextureManager {
    public global::System.Collections.Generic.Dictionary<string, global::TextureManager.CustomSprite> customSprites;
    public static global::UnityEngine.Texture2D LoadTexture(string filePath, out global::ADOFAI.LoadResult status, int maxSideSize = default) => throw null;
    public static void ShrinkImage(global::UnityEngine.Texture2D tex2D, int maxSideSize) => throw null;
    protected TextureManager() { }
    public unsafe partial class CustomSprite : global::System.IDisposable {
        public readonly global::UnityEngine.Sprite sprite;
        protected CustomSprite() { }
        void global::System.IDisposable.Dispose() => throw null;
    }
}
public enum TrackAnimationType : int {
    None = 0,
    Assemble = 1,
    Assemble_Far = 2,
    Extend = 3,
    Grow = 4,
    Grow_Spin = 5,
    Fade = 6,
    Drop = 7,
    Rise = 8,
}
public enum TrackColorType : int {
    Single = 0,
    Stripes = 1,
    Glow = 2,
    Blink = 3,
    Switch = 4,
    Rainbow = 5,
    Volume = 6,
}
public enum TrackStyle : int {
    Standard = 0,
    Neon = 1,
    NeonLight = 2,
    Basic = 3,
    Gems = 4,
    Minimal = 5,
}
public unsafe partial class VideoBloom : global::PostEffectsBase {
    public bool HighQuality;
    protected VideoBloom() { }
    public enum TweakMode : int {
        Basic = 0,
        Advanced = 1,
    }
    public enum BlendingMode : int {
        Add = 0,
        Screen = 1,
    }
}
public enum WipeDirection : int {
    StartsFromLeft = 0,
    StartsFromRight = 1,
}
public unsafe partial class WorkshopLevelList : global::UnityEngine.MonoBehaviour {
    public global::UnityEngine.UI.Image thumbnail;
    protected WorkshopLevelList() { }
}
public unsafe partial class ffxBloomPlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxBloomPlus() { }
}
public unsafe partial class ffxCheckpoint : global::ffxPlusBase {
    public virtual bool runOnHit { get => throw null; }
    public virtual void Awake() => throw null;
    public virtual void Decode(global::ADOFAI.LevelEvent evnt) => throw null;
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxCheckpoint() { }
}
public unsafe partial class ffxFlashPlus : global::ffxPlusBase {
    public global::UnityEngine.Color endColor;
    public global::UnityEngine.Color startColor;
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxFlashPlus() { }
}
public unsafe partial class ffxHallOfMirrorsPlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxHallOfMirrorsPlus() { }
}
public unsafe partial class ffxMenuPlanetSpeedChange : global::ffxPlusBase {
    public void Start() => throw null;
    protected ffxMenuPlanetSpeedChange() { }
}
public unsafe partial class ffxMoveFloorPlus : global::ffxPlusBase {
    public int end;
    public int start;
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxMoveFloorPlus() { }
}
public abstract unsafe partial class ffxPlusBase : global::ADOBase {
    public global::scrCamera cam;
    public float degreeOffset;
    public global::scrFloor floor;
    public virtual void SetStartTime(float bpm, float degreeOffset = default) => throw null;
    protected ffxPlusBase() { }
}
public unsafe partial class ffxScreenScrollPlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxScreenScrollPlus() { }
}
public unsafe partial class ffxScreenTilePlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxScreenTilePlus() { }
}
public unsafe partial class ffxSetFilterAdvancedPlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxSetFilterAdvancedPlus() { }
}
public unsafe partial class ffxSetFilterPlus : global::ffxPlusBase {
    protected ffxSetFilterPlus() { }
}
public unsafe partial class ffxShakeScreenPlus : global::ffxPlusBase {
    public virtual void StartEffect(global::scrPlanet planet) => throw null;
    protected ffxShakeScreenPlus() { }
}
public unsafe partial class scnCLS : global::ADOBase {
    public const string BackupFilename = "BackupFilename";
    public const string FeaturedLevelsLocalPath = "FeaturedLevelsLocalPath";
    public const string MainFilename = "MainFilename";
    public static global::scnCLS instance;
    public bool showingInitialMenu;
    public void DeleteLevel() => throw null;
    public void SearchLevels(string sub, bool alsoSelect = default) => throw null;
    protected scnCLS() { }
    public enum Category : int {
        Selection = 0,
        Workshop = 1,
        Featured = 2,
        Tech = 3,
    }
    public enum FeaturedLevelsSource : int {
        None = 0,
        Workshop = 1,
        DLC = 2,
        Local = 3,
    }
}
public unsafe partial class scnEditor : global::ADOBase {
    public const int MaxUndoSteps = 63;
    public bool autoFailed;
    public global::UnityEngine.UI.Image autoImage;
    public global::UnityEngine.Sprite[] autoSprites;
    public global::UnityEngine.UI.Button buttonAuto;
    public global::UnityEngine.UI.Button buttonNoFail;
    public global::UnityEngine.UI.Button buttonSave;
    public global::EditorDifficultySelector editorDifficultySelector;
    public bool inStrictlyEditingMode;
    public bool initialized;
    public static global::scnEditor instance;
    public bool isLoading;
    public global::ADOFAI.InspectorPanel levelEventsPanel;
    public static string levelToOpenOnLoad;
    public global::UnityEngine.GameObject notificationPopupContainer;
    public global::UnityEngine.UI.Button popupUnsavedChangesSave;
    public global::System.Collections.Generic.List<global::scrFloor> selectedFloors;
    public global::ADOFAI.InspectorPanel settingsPanel;
    public bool showFloorNums;
    public global::EventsArray<global::ADOFAI.LevelEvent> events { get => throw null; }
    public global::System.Collections.Generic.List<global::scrFloor> floors { get => throw null; }
    public global::ADOFAI.LevelData levelData { get => throw null; }
    public bool playMode { get => throw null; }
    public void ApplyEventsToFloors() => throw null;
    public void FlipFloor(global::scrFloor floor, bool horizontal = default, bool remakePath = default) => throw null;
    public void FlipSelection(bool horizontal = default) => throw null;
    public void OpenLevel(string filePath) => throw null;
    public void OttoBlink() => throw null;
    public void Play() => throw null;
    public void RemakePath(bool applyEventsToFloors = default, bool remakeLevel = default) => throw null;
    public void RotateFloor(global::scrFloor floor, bool CW = default, bool remakePath = default) => throw null;
    public void RotateFloor180(global::scrFloor floor, bool remakePath = default) => throw null;
    public void RotateSelection(bool CW = default) => throw null;
    public void RotateSelection180() => throw null;
    public void SaveLevel() => throw null;
    public bool SelectionIsEmpty() => throw null;
    public bool SelectionIsSingle() => throw null;
    public void SwitchToEditMode(bool clsToEditor = default) => throw null;
    public void ToggleNoFail() => throw null;
    protected scnEditor() { }
    public enum PopupType : int {
        SaveBeforeSongImport = 0,
        SaveBeforeImageImport = 1,
        SaveBeforeVideoImport = 2,
        SaveBeforeLevelExport = 3,
        ExportLevel = 4,
        MissingExportParams = 5,
        MissingFiles = 6,
        OpenURL = 7,
        CopyrightWarning = 8,
        OggEncode = 9,
        ConversionSuccessful = 10,
        ConversionError = 11,
        UnsavedChanges = 12,
        MacAppStoreFolderRestriction = 13,
        MacAppStoreFileOutsideDownloads = 14,
        Spoiler = 15,
        GenericText = 16,
        SteamDeckWarning = 17,
        BetaBranchesWorkshopPublish = 18,
        Confirm = 19,
        WorkshopLevelReupload = 20,
    }
    public enum ClipboardContent : int {
        None = 0,
        Floors = 1,
        Decorations = 2,
    }
}
public unsafe partial class scnGame : global::ADOBase {
    public const string NoTag = "NoTag";
    public int checkpointsUsed;
    public float highestBPM;
    public static global::scnGame instance;
    public global::ADOFAI.LevelData levelData;
    public void ApplyEventsToFloors(global::System.Collections.Generic.List<global::scrFloor> floors) => throw null;
    public static void ApplyEventsToFloors(global::System.Collections.Generic.List<global::scrFloor> floors, global::ADOFAI.LevelData levelData, global::scrLevelMaker lm, global::System.Collections.Generic.List<global::ADOFAI.LevelEvent> events) => throw null;
    public bool Play(int seqID = default, bool remakeFloors = default) => throw null;
    public void ResetScene(bool isResetCustomLevel = default) => throw null;
    protected scnGame() { }
}
public unsafe partial class scnLevelSelect : global::LevelSelectBase {
    public const int CrownEntrance = 65;
    public const int CrownExit = 66;
    public const int MuseDashEntrance = 67;
    public const int MuseDashExit = 68;
    protected scnLevelSelect() { }
}
public unsafe partial class scnSplash : global::ADOBase {
    protected scnSplash() { }
}
public unsafe partial class scrButtonURL : global::ADOBase {
    public global::UnityEngine.UI.Button button;
    protected scrButtonURL() { }
}
public unsafe partial class scrCamera : global::ADOBase {
    public const float DefaultCameraOrthoSize = 69f;
    public void SetCustomFrameRate(bool enable, float frame = default) => throw null;
    protected scrCamera() { }
}
public unsafe partial class scrConductor : global::ADOBase {
    public double addoffset;
    public float bpm;
    public float countdownSpeedMultiplier;
    public int countdownTicks;
    public double crotchetAtStart;
    public static global::CalibrationPreset currentPreset;
    public double deltaSongPos;
    public double dspTime;
    public double dspTimeSong;
    public bool fastTakeoff;
    public global::UnityEngine.Audio.AudioMixerGroup hitSoundGroup;
    public float hitSoundVolume;
    public bool isGameWorld;
    public bool playEndingCymbal;
    public double prev_dspTime;
    public bool separateCountdownTime;
    public global::UnityEngine.AudioSource song;
    public global::UnityEngine.AudioSource song2;
    public global::UnityEngine.AudioSource song3;
    public static float calibration_i { get => throw null; }
    public static global::scrConductor instance { get => throw null; }
    public double songposition_minusi { get => throw null; set { } }
    public double GetCountdownTime(int i) => throw null;
    public void KillAllSounds() => throw null;
    public void PlayHitTimes() => throw null;
    public static void SaveCurrentPreset() => throw null;
    public void ScrubMusicToTime(double newTime) => throw null;
    public void SetupConductorWithLevelData(global::ADOFAI.LevelData levelData) => throw null;
    protected scrConductor() { }
    public enum DuckState : int {
        None = 0,
        Starting = 1,
        Ducked = 2,
        Stopping = 3,
    }
}
public unsafe partial class scrController : global::MonsterLove.StateMachine.StateBehaviour {
    public const bool HallOfMirrorsUsesRenderTextures = false;
    public const float boothModeDebounceCooldownTime = 71f;
    public static int checkpointsUsed;
    public int currentSeqID;
    public global::System.Collections.Generic.List<global::PlanetRenderer> dummyPlanets;
    public global::scrFloor firstFloor;
    public bool gameworld;
    public bool goShown;
    public bool noFail;
    public global::PauseMenu pauseMenu;
    public float startVolume;
    public global::UnityEngine.UI.Text txtAllStrictClear;
    public global::UnityEngine.UI.Text txtCongrats;
    public global::UnityEngine.UI.Text txtLevelName;
    public global::scrFloor currFloor { get => throw null; }
    public static global::scrController instance { get => throw null; }
    public bool paused { get => throw null; set { } }
    public float percentComplete { get => throw null; }
    public global::scrPlayer playerOne { get => throw null; }
    public float tileSize { get => throw null; }
    public void EnterLevel(string worldAndLevel, bool speedTrial = default) => throw null;
    public void FailAction(bool overload = default, bool multipress = default, string failMessage = default, bool hitbox = default) => throw null;
    public void OnLandOnPortal(global::scrPlanet planetThatWon, global::Portal portalDestination, string portalArguments) => throw null;
    public void QuitToMainMenu() => throw null;
    public void Restart(bool fromBeginning = default) => throw null;
    public void RestartProgress() => throw null;
    public void Scrub(int floorNum, bool forceDontStartMusicFourTilesBefore = default) => throw null;
    public void SetPracticeMode(bool practice) => throw null;
    public void StartLoadingScene(global::WipeDirection wipeDirection = default) => throw null;
    public void Start_Rewind(int _currentSeqID = default) => throw null;
    public bool TogglePauseGame() => throw null;
    public void UpdateInput() => throw null;
    public global::System.Collections.IEnumerator WaitForStartCo(int seqID = default, bool remakeFloors = default) => throw null;
    protected scrController() { }
}
public unsafe partial class scrCountdown : global::ADOBase {
    public void CancelGo() => throw null;
    protected scrCountdown() { }
}
public abstract unsafe partial class scrDecoration : global::ADOBase {
    public const int HitboxLayer = 72;
    public bool forceHide;
    public global::DecPlacementType placementType;
    public virtual bool GetVisible() => throw null;
    public virtual void SetVisible(bool visible) => throw null;
    protected scrDecoration() { }
}
public unsafe partial class scrDecorationManager : global::ADOBase {
    public global::System.Collections.Generic.List<global::scrDecoration> allDecorations;
    public global::TextureManager imageHolder;
    public static global::scrDecorationManager instance { get => throw null; }
    public static global::scrDecoration GetDecoration(global::ADOFAI.LevelEvent source) => throw null;
    protected scrDecorationManager() { }
}
public unsafe partial class scrFlash : global::UnityEngine.MonoBehaviour {
    public static void FlashEx(global::UnityEngine.Color _colorStart, global::UnityEngine.Color _colorEnd, float duration = default) => throw null;
    protected scrFlash() { }
}
public unsafe partial class scrFloor : global::ADOBase {
    public const int SortingOrderOffset = 73;
    public double angleLength;
    public bool auto;
    public global::UnityEngine.SpriteRenderer bottomGlow;
    public const string checkpointIconFilename = "checkpointIconFilename";
    public bool disableGlow;
    public global::scrLetterPress editorNumText;
    public double entryTime;
    public double entryangle;
    public double exitangle;
    public float floatDirection;
    public global::FloorIcon floorIcon;
    public global::FloorRenderer floorRenderer;
    public const string gizmoIconFilename = "gizmoIconFilename";
    public global::scrHoldRenderer holdRenderer;
    public global::UnityEngine.SpriteRenderer iconsprite;
    public bool isCCW;
    public bool isportal;
    public global::UnityEngine.SpriteRenderer legacyFloorSpriteRenderer;
    public double marginScale;
    public bool midSpin;
    public global::UnityEngine.LineRenderer multiplanetLine;
    public global::scrFloor nextfloor;
    public int numPlanets;
    public float opacity;
    public bool outline;
    public global::UnityEngine.SpriteRenderer outlineSprite;
    public float radiusScale;
    public int seqID;
    public global::TrackColorType specialColorType;
    public float speed;
    public global::UnityEngine.Vector3 startPos;
    public bool stickToFloor;
    public char stringDirection;
    public global::UnityEngine.SpriteRenderer topGlow;
    public void LightUp(global::HitMargin hitmargin = default) => throw null;
    public void SetIconAngle(float radians) => throw null;
    public void SetIconFlipped(bool flipped) => throw null;
    public void SetIconOutlineSprite(global::UnityEngine.Sprite sprite) => throw null;
    public void SetIconSprite(global::UnityEngine.Sprite sprite) => throw null;
    public void SetToRandomColor() => throw null;
    public void Start() => throw null;
    public void UpdateIconSprite(bool resetToDefault = default) => throw null;
    protected scrFloor() { }
}
public unsafe partial class scrHUDText : global::UnityEngine.MonoBehaviour {
    public bool isTitle;
    protected scrHUDText() { }
}
public unsafe partial class scrHitTextMesh : global::ADOBase {
    public bool dead;
    public global::HitMargin hitMargin;
    public void Show(global::UnityEngine.Vector3 position, global::UnityEngine.Vector3 borderOffset = default, float missAngle = default, float scale = default, float angle = default, float fadeSpeed = default) => throw null;
    protected scrHitTextMesh() { }
}
public unsafe partial class scrHoldRenderer : global::ADOBase {
    public global::UnityEngine.MeshRenderer m_meshRenderer;
    protected scrHoldRenderer() { }
}
public unsafe partial class scrLetterPress : global::UnityEngine.MonoBehaviour {
    protected scrLetterPress() { }
}
public unsafe partial class scrLevelMaker : global::ADOBase {
    public const double FloorAngleEpsilon = 76d;
    public const string FloorContainerName = "FloorContainerName";
    public float[] floorAngles;
    public bool isOldLevel;
    public string leveldata;
    public global::System.Collections.Generic.List<global::scrFloor> listFloors;
    public global::scrLevelMaker2 lm2;
    public static global::scrLevelMaker instance { get => throw null; }
    public void CalculateFloorEntryTimes() => throw null;
    public double CalculateSingleFloorAngleLength(global::scrFloor cf) => throw null;
    protected scrLevelMaker() { }
}
public unsafe partial class scrLevelMaker2 : global::UnityEngine.MonoBehaviour {
    public bool BigTiles;
    protected scrLevelMaker2() { }
}
public unsafe partial class scrLogoText : global::UnityEngine.MonoBehaviour {
    public static global::scrLogoText instance;
    public void LateUpdate() => throw null;
    public void UpdateColors() => throw null;
    protected scrLogoText() { }
}
public static unsafe partial class scrMisc {
    public static double GetAngleMoved(double entryAngle, double exitAngle, bool isCW) => throw null;
    public static global::HitMargin GetHitMargin(float hitangle, float refangle, bool isCW, float bpmTimesSpeed, float conductorPitch, double marginScale = default) => throw null;
    public static double mod(double x, double m) => throw null;
}
public unsafe partial class scrMistakesManager : global::ADOClass {
    public void MarkCheckpoint(int checkpointTileOffset) => throw null;
    public void RevertToLastCheckpoint() => throw null;
    protected scrMistakesManager() { }
}
public unsafe partial class scrPlanet : global::ADOBase {
    public double angle;
    public const float basePlanetScale = 78f;
    public float cosmeticAngle;
    public float cosmeticRadius;
    public global::scrFloor currfloor;
    public global::scrPlanet other;
    public int planetIndex;
    public global::PlanetRenderer planetRenderer;
    public global::PlanetarySystem planetarySystem;
    public global::scrPlayer player;
    public double snappedLastAngle { get => throw null; }
    public double targetExitAngle { get => throw null; }
    public void Update_RefreshAngles() => throw null;
    protected scrPlanet() { }
}
public unsafe partial class scrPlayer : global::ADOBase {
    public bool alive;
    public global::System.Collections.Generic.List<double> keyTimes;
    public double lastHit;
    public float lockInput;
    public global::PlanetarySystem planetarySystem;
    public bool responsive;
    public global::scrFloor currFloor { get => throw null; }
    public bool Hit(bool isAuto = default) => throw null;
    public void UnlockInput() => throw null;
    public bool ValidInputWasTriggered() => throw null;
    protected scrPlayer() { }
}
public unsafe partial class scrPlayerManager : global::ADOBase {
    public const int MaxPlayers = 79;
    public global::System.Collections.Generic.IEnumerator<global::scrPlayer> GetEnumerator() => throw null;
    protected scrPlayerManager() { }
}
public unsafe partial class scrPressToStart : global::ADOBase {
    public void HideText() => throw null;
    protected scrPressToStart() { }
}
public unsafe partial class scrRing : global::ADOBase {
    public void Switch(bool chosen, bool instant = default) => throw null;
    protected scrRing() { }
}
public unsafe partial class scrSfx : global::ADOBase {
    protected scrSfx() { }
}
public unsafe partial class scrShowIfDebug : global::ADOBase {
    protected scrShowIfDebug() { }
}
public unsafe partial class scrUIController : global::ADOBase {
    public global::UnityEngine.UI.Button difficultyButtonLeft;
    public global::UnityEngine.UI.Button difficultyButtonRight;
    public global::UnityEngine.RectTransform difficultyContainer;
    public global::UnityEngine.CanvasGroup difficultyFadeContainer;
    public global::UnityEngine.UI.Image difficultyImage;
    public global::UnityEngine.UI.Image noFailImage;
    public global::UnityEngine.UI.Text txtLevelName;
    public static global::scrUIController instance { get => throw null; }
    public void DifficultyArrowPressed(bool rightPressed) => throw null;
    public void ShowDifficultyContainer(global::DifficultyUIMode mode) => throw null;
    protected scrUIController() { }
}
public unsafe partial class scrVfxPlus : global::ADOBase {
    public global::System.Collections.Generic.List<global::DG.Tweening.Tween> pausedTweens;
    public static global::scrVfxPlus instance { get => throw null; }
    public void ScrubToTime(float t) => throw null;
    protected scrVfxPlus() { }
}
public unsafe partial class scrVisualDecoration : global::scrDecoration {
    public global::UnityEngine.RenderTexture spareRT1;
    public global::UnityEngine.RenderTexture spareRT2;
    public global::UnityEngine.SpriteRenderer spriteRenderer;
    protected scrVisualDecoration() { }
}
namespace ADOFAI {
    public unsafe partial class InspectorPanel : global::ADOBase {
        public int cacheEventIndex;
        public global::System.Collections.Generic.List<global::ADOFAI.PropertiesPanel> panelsList;
        public global::ADOFAI.LevelEventType selectedEventType;
        public const float tabHeight = 80f;
        public global::UnityEngine.RectTransform tabs;
        public void HideAllInspectorTabs() => throw null;
        public void Init(global::System.Collections.Generic.Dictionary<string, global::ADOFAI.LevelEventInfo> levelEventsInfo, bool floorPanel) => throw null;
        public void ShowInspector(bool show, bool forceAction = default) => throw null;
        public void ShowPanel(global::ADOFAI.LevelEventType eventType, int eventIndex = default) => throw null;
        protected InspectorPanel() { }
    }
    public unsafe partial class LevelData {
        public global::ADOFAI.LevelEvent backgroundSettings;
        public global::ADOFAI.LevelEvent cameraSettings;
        public global::ADOFAI.LevelEvent decorationSettings;
        public global::DecorationsArray<global::ADOFAI.LevelEvent> decorations;
        public global::EventsArray<global::ADOFAI.LevelEvent> levelEvents;
        public global::ADOFAI.LevelEvent miscSettings;
        public global::ADOFAI.LevelEvent songSettings;
        public global::ADOFAI.LevelEvent trackSettings;
        public string artist { get => throw null; set { } }
        public float bpm { get => throw null; }
        public int pitch { get => throw null; }
        public string song { get => throw null; }
        public void Decode(global::System.Collections.Generic.Dictionary<string, object> dict, out global::ADOFAI.LoadResult status) => throw null;
        protected LevelData() { }
    }
    public unsafe partial class LevelEvent {
        public const int NoFloor = 81;
        public bool active;
        public global::ADOFAI.LevelEventType eventType;
        public int floor;
        public object this[string key] { get => throw null; set { } }
        public LevelEvent(int newFloor, global::ADOFAI.LevelEventType type, global::ADOFAI.LevelEventInfo customInfo) => throw null;
        public float GetFloat(string key) => throw null;
        public int GetInt(string key) => throw null;
        public string GetString(string key) => throw null;
        protected LevelEvent() { }
        public enum DecodeResult : int {
            Success = 0,
            NoTypeFound = 1,
            NeedsTaroDLC = 2,
        }
    }
    public unsafe partial class LevelEventInfo {
        protected LevelEventInfo() { }
    }
    public enum LevelEventType : int {
        None = 0,
        SetSpeed = 1,
        Twirl = 2,
        Checkpoint = 3,
        LevelSettings = 4,
        SongSettings = 5,
        TrackSettings = 6,
        BackgroundSettings = 7,
        CameraSettings = 8,
        MiscSettings = 9,
        EventSettings = 10,
        DecorationSettings = 11,
        MoveCamera = 12,
        CustomBackground = 13,
        ChangeTrack = 14,
        ColorTrack = 15,
        AnimateTrack = 16,
        RecolorTrack = 17,
        MoveTrack = 18,
        AddDecoration = 19,
        AddText = 20,
        SetText = 21,
        Flash = 22,
        SetHitsound = 23,
        SetFilter = 24,
        SetFilterAdvanced = 25,
        SetPlanetRotation = 26,
        HallOfMirrors = 27,
        ShakeScreen = 28,
        MoveDecorations = 29,
        PositionTrack = 30,
        RepeatEvents = 31,
        Bloom = 32,
        Hold = 33,
        SetHoldSound = 34,
        SetConditionalEvents = 35,
        ScreenTile = 36,
        ScreenScroll = 37,
        EditorComment = 38,
        Bookmark = 39,
        CallMethod = 40,
        AddComponent = 41,
        PlaySound = 42,
        MultiPlanet = 43,
        FreeRoam = 44,
        FreeRoamTwirl = 45,
        FreeRoamRemove = 46,
        FreeRoamWarning = 47,
        Pause = 48,
        AutoPlayTiles = 49,
        Hide = 50,
        ScaleMargin = 51,
        ScaleRadius = 52,
        Multitap = 53,
        TileDimensions = 54,
        KillPlayer = 55,
        ScalePlanets = 56,
        SetFloorIcon = 57,
        AddObject = 58,
        SetObject = 59,
        SetDefaultText = 60,
        SetFrameRate = 61,
        AddParticle = 62,
        SetParticle = 63,
        EmitParticle = 64,
        SetInputEvent = 65,
    }
    public unsafe partial class ListItem : global::ADOBase {
        public global::UnityEngine.UI.Image itemTypeImage;
        public global::ADOFAI.LevelEvent sourceLevelEvent;
        public global::UnityEngine.UI.Image tagImage;
        protected ListItem() { }
    }
    public unsafe partial class ListItem_Decoration : global::ADOFAI.ListItem {
        public global::UnityEngine.Sprite objectSprite;
        public global::UnityEngine.Sprite particleSprite;
        public global::UnityEngine.Sprite textSprite;
        public virtual void SetEvent(global::ADOFAI.LevelEvent ev) => throw null;
        protected virtual void ShowSelectionBackground(bool selected) => throw null;
        protected ListItem_Decoration() { }
    }
    public enum LoadResult : int {
        Successful = 0,
        FutureVersion = 1,
        ModRequired = 2,
        Error = 3,
        TaroDLCRequired = 4,
        UnauthorizedAccess = 5,
        MissingFile = 6,
    }
    public unsafe partial class PropertiesPanel : global::ADOBase {
        protected PropertiesPanel() { }
    }
    public unsafe partial class Property : global::UnityEngine.MonoBehaviour {
        public global::UnityEngine.RectTransform controlContainer;
        public global::TMPro.TMP_Text label;
        protected Property() { }
    }
}
namespace ADOFAI.Editor.Actions {
    public abstract unsafe partial class EditorAction {
        protected EditorAction() { }
    }
    public unsafe partial class SaveLevelEditorAction : global::ADOFAI.Editor.Actions.EditorAction {
        public virtual void Execute(global::scnEditor editor) => throw null;
        protected SaveLevelEditorAction() { }
    }
}
namespace MonsterLove.StateMachine {
    public unsafe partial class StateBehaviour : global::ADOBase {
        public global::MonsterLove.StateMachine.StateEngine stateMachine { get => throw null; }
        public virtual void ChangeState(global::System.Enum newState) => throw null;
        protected virtual void ChangeState(global::System.Enum newState, global::MonsterLove.StateMachine.StateTransition transition) => throw null;
        protected StateBehaviour() { }
    }
    public unsafe partial class StateEngine : global::UnityEngine.MonoBehaviour {
        public global::System.Enum GetState() => throw null;
        protected StateEngine() { }
    }
    public enum StateTransition : int {
        Overwrite = 0,
        Safe = 1,
    }
}
