// <auto-generated>
//   Compile-only stand-in for "UnityEngine.TextRenderingModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine {
    public sealed unsafe partial class Font : global::UnityEngine.Object {
        public Font(string name) => throw null;
        private Font() { }
    }
    public enum FontStyle : int {
        Normal = 0,
        Bold = 1,
        Italic = 2,
        BoldAndItalic = 3,
    }
    public enum HorizontalWrapMode : int {
        Wrap = 0,
        Overflow = 1,
    }
    public enum TextAnchor : int {
        UpperLeft = 0,
        UpperCenter = 1,
        UpperRight = 2,
        MiddleLeft = 3,
        MiddleCenter = 4,
        MiddleRight = 5,
        LowerLeft = 6,
        LowerCenter = 7,
        LowerRight = 8,
    }
    public sealed unsafe partial class TextMesh : global::UnityEngine.Component {
        private TextMesh() { }
    }
    public unsafe partial struct UIVertex {
        public global::UnityEngine.Color32 color;
        public global::UnityEngine.Vector3 normal;
        public global::UnityEngine.Vector3 position;
        public static global::UnityEngine.UIVertex simpleVert;
        public global::UnityEngine.Vector4 tangent;
        public global::UnityEngine.Vector4 uv0;
        public global::UnityEngine.Vector4 uv1;
        public global::UnityEngine.Vector4 uv2;
        public global::UnityEngine.Vector4 uv3;
    }
    public enum VerticalWrapMode : int {
        Truncate = 0,
        Overflow = 1,
    }
}
