// <auto-generated>
//   Compile-only stand-in for "Assembly-CSharp-firstpass", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

public enum AudioOutputType : int {
    Speaker = 0,
    Wired = 1,
    Bluetooth = 2,
    Other = 3,
    NotSet = -1,
    Any = -2,
}
public enum DifficultyUIMode : int {
    DontShow = 0,
    ShowLenientAndNormal = 1,
    ShowNormalAndStrict = 2,
    ShowAll = 3,
}
namespace DG.Tweening {
    public static unsafe partial class DOTweenModuleUI {
        public static global::DG.Tweening.Core.TweenerCore<float, float, global::DG.Tweening.Plugins.Options.FloatOptions> DOFade(this global::UnityEngine.CanvasGroup target, float endValue, float duration) => throw null;
        public static global::DG.Tweening.Core.TweenerCore<global::UnityEngine.Vector2, global::UnityEngine.Vector2, global::DG.Tweening.Plugins.Options.VectorOptions> DOPivotY(this global::UnityEngine.RectTransform target, float endValue, float duration) => throw null;
    }
}
