// <auto-generated>
//   Compile-only stand-in for "UnityEngine.UIElementsModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine.UIElements {
    public abstract unsafe partial class CallbackEventHandler {
        protected CallbackEventHandler() { }
    }
    public abstract unsafe partial class Focusable : global::UnityEngine.UIElements.CallbackEventHandler {
        protected Focusable() { }
    }
    public unsafe partial interface IEventHandler {
    }
    public unsafe partial interface IExperimentalFeatures {
    }
    public unsafe partial interface IResolvedStyle {
    }
    public unsafe partial interface IStylePropertyAnimations {
    }
    public unsafe partial interface ITransform {
    }
    public unsafe partial interface IVisualElementScheduler {
    }
    public sealed unsafe partial class UIDocument : global::UnityEngine.MonoBehaviour {
        private UIDocument() { }
        public enum WorldSpaceSizeMode : int {
            Dynamic = 0,
            Fixed = 1,
        }
    }
    public unsafe partial class VisualElement : global::UnityEngine.UIElements.Focusable {
        protected VisualElement() { }
        public enum MeasureMode : int {
            Undefined = 0,
            Exactly = 1,
            AtMost = 2,
        }
    }
}
namespace UnityEngine.UIElements.Experimental {
    public unsafe partial interface ITransitionAnimations {
    }
}
