// <auto-generated>
//   Compile-only stand-in for "UnityEngine.ParticleSystemModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine {
    public sealed unsafe partial class ParticleSystem : global::UnityEngine.Component {
        public global::UnityEngine.ParticleSystem.EmissionModule emission { get => throw null; }
        public global::UnityEngine.ParticleSystem.MainModule main { get => throw null; }
        public void Clear(bool withChildren) => throw null;
        public void Stop(bool withChildren, global::UnityEngine.ParticleSystemStopBehavior stopBehavior) => throw null;
        private ParticleSystem() { }
        public unsafe partial struct MainModule {
            private global::UnityEngine.ParticleSystem m_ParticleSystem;
            public int maxParticles { get => throw null; set { } }
            public global::UnityEngine.ParticleSystem.MinMaxGradient startColor { get => throw null; set { } }
        }
        public unsafe partial struct EmissionModule {
            private global::UnityEngine.ParticleSystem m_ParticleSystem;
            public bool enabled { get => throw null; set { } }
            public global::UnityEngine.ParticleSystem.MinMaxCurve rateOverTime { get => throw null; set { } }
        }
        public unsafe partial struct MinMaxCurve {
            private float m_ConstantMax;
            private float m_ConstantMin;
            private global::UnityEngine.AnimationCurve m_CurveMax;
            private global::UnityEngine.AnimationCurve m_CurveMin;
            private float m_CurveMultiplier;
            private global::UnityEngine.ParticleSystemCurveMode m_Mode;
            public static implicit operator global::UnityEngine.ParticleSystem.MinMaxCurve(float constant) => throw null;
        }
        public unsafe partial struct MinMaxGradient {
            private global::UnityEngine.Color m_ColorMax;
            private global::UnityEngine.Color m_ColorMin;
            private global::UnityEngine.Gradient m_GradientMax;
            private global::UnityEngine.Gradient m_GradientMin;
            private global::UnityEngine.ParticleSystemGradientMode m_Mode;
            public MinMaxGradient(global::UnityEngine.Color color) => throw null;
        }
    }
    public enum ParticleSystemCurveMode : int {
        Constant = 0,
        Curve = 1,
        TwoCurves = 2,
        TwoConstants = 3,
    }
    public enum ParticleSystemGradientMode : int {
        Color = 0,
        Gradient = 1,
        TwoColors = 2,
        TwoGradients = 3,
        RandomColor = 4,
    }
    public enum ParticleSystemStopBehavior : int {
        StopEmittingAndClear = 0,
        StopEmitting = 1,
    }
}
