// <auto-generated>
//   Compile-only stand-in for "UnityEngine.InputLegacyModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine {
    public unsafe partial class Input {
        public static bool anyKeyDown { get => throw null; }
        public static string inputString { get => throw null; }
        public static global::UnityEngine.Vector3 mousePosition { get => throw null; }
        public static global::UnityEngine.Vector2 mouseScrollDelta { get => throw null; }
        public static float GetAxisRaw(string axisName) => throw null;
        public static bool GetKey(global::UnityEngine.KeyCode key) => throw null;
        public static bool GetKeyDown(global::UnityEngine.KeyCode key) => throw null;
        public static bool GetKeyUp(global::UnityEngine.KeyCode key) => throw null;
        public static bool GetMouseButton(int button) => throw null;
        public static bool GetMouseButtonDown(int button) => throw null;
        public static bool GetMouseButtonUp(int button) => throw null;
        protected Input() { }
    }
}
