// <auto-generated>
//   Compile-only stand-in for "DOTween", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace DG.Tweening {
    public enum AxisConstraint : int {
        None = 0,
        X = 2,
        Y = 4,
        Z = 8,
        W = 16,
    }
    public unsafe partial class DOTween {
        public static global::DG.Tweening.Sequence Sequence() => throw null;
        protected DOTween() { }
    }
    public enum Ease : int {
        Unset = 0,
        Linear = 1,
        InSine = 2,
        OutSine = 3,
        InOutSine = 4,
        InQuad = 5,
        OutQuad = 6,
        InOutQuad = 7,
        InCubic = 8,
        OutCubic = 9,
        InOutCubic = 10,
        InQuart = 11,
        OutQuart = 12,
        InOutQuart = 13,
        InQuint = 14,
        OutQuint = 15,
        InOutQuint = 16,
        InExpo = 17,
        OutExpo = 18,
        InOutExpo = 19,
        InCirc = 20,
        OutCirc = 21,
        InOutCirc = 22,
        InElastic = 23,
        OutElastic = 24,
        InOutElastic = 25,
        InBack = 26,
        OutBack = 27,
        InOutBack = 28,
        InBounce = 29,
        OutBounce = 30,
        InOutBounce = 31,
        Flash = 32,
        InFlash = 33,
        OutFlash = 34,
        InOutFlash = 35,
        INTERNAL_Zero = 36,
        INTERNAL_Custom = 37,
    }
    public sealed unsafe partial class Sequence : global::DG.Tweening.Tween {
        private Sequence() { }
    }
    public static unsafe partial class ShortcutExtensions {
        public static int DOKill(this global::UnityEngine.Component target, bool complete = default) => throw null;
    }
    public abstract unsafe partial class Tween : global::DG.Tweening.Core.ABSSequentiable {
        protected Tween() { }
    }
    public unsafe delegate void TweenCallback();
    public static unsafe partial class TweenExtensions {
        public static void Kill(this global::DG.Tweening.Tween t, bool complete = default) => throw null;
    }
    public static unsafe partial class TweenSettingsExtensions {
        public static global::DG.Tweening.Sequence Insert(this global::DG.Tweening.Sequence s, float atPosition, global::DG.Tweening.Tween t) => throw null;
        public static T OnComplete<T>(this T t, global::DG.Tweening.TweenCallback action) where T : global::DG.Tweening.Tween => throw null;
        public static T SetEase<T>(this T t, global::DG.Tweening.Ease ease) where T : global::DG.Tweening.Tween => throw null;
    }
    public abstract unsafe partial class Tweener : global::DG.Tweening.Tween {
        protected Tweener() { }
    }
}
namespace DG.Tweening.Core {
    public abstract unsafe partial class ABSSequentiable {
        protected ABSSequentiable() { }
    }
    public unsafe partial class TweenerCore<T1, T2, TPlugOptions> : global::DG.Tweening.Tweener where TPlugOptions : struct, global::DG.Tweening.Plugins.Options.IPlugOptions {
        protected TweenerCore() { }
    }
}
namespace DG.Tweening.Plugins.Options {
    public unsafe partial struct FloatOptions : global::DG.Tweening.Plugins.Options.IPlugOptions {
        public bool snapping;
        void global::DG.Tweening.Plugins.Options.IPlugOptions.Reset() => throw null;
    }
    public unsafe partial interface IPlugOptions {
        void Reset();
    }
    public unsafe partial struct VectorOptions : global::DG.Tweening.Plugins.Options.IPlugOptions {
        public global::DG.Tweening.AxisConstraint axisConstraint;
        public bool snapping;
        void global::DG.Tweening.Plugins.Options.IPlugOptions.Reset() => throw null;
    }
}
