// <auto-generated>
//   Compile-only stand-in for "Unity.TextMeshPro", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace TMPro {
    public enum FontStyles : int {
        Normal = 0,
        Bold = 1,
        Italic = 2,
        Underline = 4,
        LowerCase = 8,
        UpperCase = 16,
        SmallCaps = 32,
        Strikethrough = 64,
        Superscript = 128,
        Subscript = 256,
        Highlight = 512,
    }
    public unsafe partial struct HighlightState {
        public global::UnityEngine.Color32 color;
        public global::TMPro.TMP_Offset padding;
    }
    public static unsafe partial class ShaderUtilities {
        public static int ID_OutlineColor;
        public static int ID_OutlineWidth;
    }
    public abstract unsafe partial class TMP_Asset : global::UnityEngine.ScriptableObject {
        public global::UnityEngine.Material material { get => throw null; set { } }
        protected TMP_Asset() { }
    }
    public unsafe partial class TMP_Character : global::TMPro.TMP_TextElement {
        protected TMP_Character() { }
    }
    public unsafe partial struct TMP_CharacterInfo {
        private float adjustedAscender;
        private float adjustedDescender;
        private float adjustedHorizontalAdvance;
        public global::UnityEngine.TextCore.Glyph alternativeGlyph;
        public float ascender;
        public float aspectRatio;
        public float baseLine;
        public global::UnityEngine.Vector3 bottomLeft;
        public global::UnityEngine.Vector3 bottomRight;
        public char character;
        public global::UnityEngine.Color32 color;
        public float descender;
        public global::TMPro.TMP_TextElementType elementType;
        public global::TMPro.TMP_FontAsset fontAsset;
        public global::UnityEngine.Color32 highlightColor;
        public global::TMPro.HighlightState highlightState;
        public int index;
        public bool isUsingAlternateTypeface;
        public bool isVisible;
        public int lineNumber;
        public global::UnityEngine.Material material;
        public int materialReferenceIndex;
        public float origin;
        public int pageNumber;
        public float pointSize;
        public float scale;
        public global::UnityEngine.Color32 strikethroughColor;
        public int strikethroughVertexIndex;
        public int stringLength;
        public global::TMPro.FontStyles style;
        public global::TMPro.TMP_TextElement textElement;
        public global::UnityEngine.Vector3 topLeft;
        public global::UnityEngine.Vector3 topRight;
        public global::UnityEngine.Color32 underlineColor;
        public int underlineVertexIndex;
        public int vertexIndex;
        public global::TMPro.TMP_Vertex vertex_BL;
        public global::TMPro.TMP_Vertex vertex_BR;
        public global::TMPro.TMP_Vertex vertex_TL;
        public global::TMPro.TMP_Vertex vertex_TR;
        public float xAdvance;
    }
    public unsafe partial class TMP_FontAsset : global::TMPro.TMP_Asset {
        public global::UnityEngine.Texture2D[] atlasTextures { get => throw null; set { } }
        public global::System.Collections.Generic.List<global::TMPro.TMP_Character> characterTable { get => throw null; }
        public global::System.Collections.Generic.List<global::TMPro.TMP_FontAsset> fallbackFontAssetTable { get => throw null; set { } }
        public bool isMultiAtlasTexturesEnabled { get => throw null; set { } }
        public static global::TMPro.TMP_FontAsset CreateFontAsset(global::UnityEngine.Font font) => throw null;
        public bool HasCharacter(char character, bool searchFallbacks = default, bool tryAddCharacter = default) => throw null;
        protected TMP_FontAsset() { }
    }
    public unsafe partial class TMP_InputField : global::UnityEngine.UI.Selectable, global::UnityEngine.EventSystems.IBeginDragHandler, global::UnityEngine.EventSystems.IDragHandler, global::UnityEngine.EventSystems.IEndDragHandler, global::UnityEngine.EventSystems.IPointerClickHandler {
        public float caretBlinkRate { get => throw null; set { } }
        public global::UnityEngine.Color caretColor { get => throw null; set { } }
        public int caretWidth { get => throw null; set { } }
        public int characterLimit { get => throw null; set { } }
        public global::TMPro.TMP_InputField.ContentType contentType { get => throw null; set { } }
        public bool customCaretColor { get => throw null; set { } }
        public bool isFocused { get => throw null; }
        public global::TMPro.TMP_InputField.LineType lineType { get => throw null; set { } }
        public global::TMPro.TMP_InputField.SelectionEvent onDeselect { get => throw null; set { } }
        public global::TMPro.TMP_InputField.SubmitEvent onEndEdit { get => throw null; set { } }
        public bool onFocusSelectAll { get => throw null; set { } }
        public global::TMPro.TMP_InputField.OnChangeEvent onValueChanged { get => throw null; set { } }
        public global::UnityEngine.UI.Graphic placeholder { get => throw null; set { } }
        public bool richText { get => throw null; set { } }
        public global::UnityEngine.Color selectionColor { get => throw null; set { } }
        public string text { get => throw null; set { } }
        public global::TMPro.TMP_Text textComponent { get => throw null; set { } }
        public global::UnityEngine.RectTransform textViewport { get => throw null; set { } }
        public void ActivateInputField() => throw null;
        public void SetTextWithoutNotify(string input) => throw null;
        protected TMP_InputField() { }
        void global::UnityEngine.EventSystems.IBeginDragHandler.OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IDragHandler.OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IEndDragHandler.OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public enum ContentType : int {
            Standard = 0,
            Autocorrected = 1,
            IntegerNumber = 2,
            DecimalNumber = 3,
            Alphanumeric = 4,
            Name = 5,
            EmailAddress = 6,
            Password = 7,
            Pin = 8,
            Custom = 9,
        }
        public enum InputType : int {
            Standard = 0,
            AutoCorrect = 1,
            Password = 2,
        }
        public enum CharacterValidation : int {
            None = 0,
            Digit = 1,
            Integer = 2,
            Decimal = 3,
            Alphanumeric = 4,
            Name = 5,
            Regex = 6,
            EmailAddress = 7,
            CustomValidator = 8,
        }
        public enum LineType : int {
            SingleLine = 0,
            MultiLineSubmit = 1,
            MultiLineNewline = 2,
        }
        public unsafe partial class SubmitEvent : global::UnityEngine.Events.UnityEvent<string> {
            protected SubmitEvent() { }
        }
        public unsafe partial class OnChangeEvent : global::UnityEngine.Events.UnityEvent<string> {
            protected OnChangeEvent() { }
        }
        public unsafe partial class SelectionEvent : global::UnityEngine.Events.UnityEvent<string> {
            protected SelectionEvent() { }
        }
        public enum EditState : int {
            Continue = 0,
            Finish = 1,
        }
    }
    public unsafe partial struct TMP_MeshInfo {
        public global::UnityEngine.Color32[] colors32;
        public global::UnityEngine.Material material;
        public global::UnityEngine.Mesh mesh;
        public global::UnityEngine.Vector3[] normals;
        public global::UnityEngine.Vector4[] tangents;
        public int[] triangles;
        public global::UnityEngine.Vector4[] uvs0;
        public global::UnityEngine.Vector2[] uvs2;
        public int vertexCount;
        public global::UnityEngine.Vector3[] vertices;
    }
    public unsafe partial struct TMP_Offset {
        private float m_Bottom;
        private float m_Left;
        private float m_Right;
        private float m_Top;
    }
    public unsafe partial class TMP_Settings : global::UnityEngine.ScriptableObject {
        public static global::TMPro.TMP_SpriteAsset defaultSpriteAsset { get => throw null; set { } }
        public static global::TMPro.TMP_Settings instance { get => throw null; }
        protected TMP_Settings() { }
    }
    public unsafe partial class TMP_Sprite : global::TMPro.TMP_TextElement_Legacy {
        protected TMP_Sprite() { }
    }
    public unsafe partial class TMP_SpriteAsset : global::TMPro.TMP_Asset {
        public global::System.Collections.Generic.List<global::TMPro.TMP_Sprite> spriteInfoList;
        public global::UnityEngine.Texture spriteSheet;
        public global::System.Collections.Generic.List<global::TMPro.TMP_SpriteCharacter> spriteCharacterTable { get => throw null; }
        public global::System.Collections.Generic.List<global::TMPro.TMP_SpriteGlyph> spriteGlyphTable { get => throw null; }
        public void UpdateLookupTables() => throw null;
        protected TMP_SpriteAsset() { }
    }
    public unsafe partial class TMP_SpriteCharacter : global::TMPro.TMP_TextElement {
        public string name { get => throw null; set { } }
        public TMP_SpriteCharacter(uint unicode, global::TMPro.TMP_SpriteGlyph glyph) => throw null;
        protected TMP_SpriteCharacter() { }
    }
    public unsafe partial class TMP_SpriteGlyph : global::UnityEngine.TextCore.Glyph {
        public TMP_SpriteGlyph() => throw null;
    }
    public abstract unsafe partial class TMP_Text : global::UnityEngine.UI.MaskableGraphic {
        public global::TMPro.TextAlignmentOptions alignment { get => throw null; set { } }
        public float alpha { get => throw null; set { } }
        public float characterSpacing { get => throw null; set { } }
        public bool enableAutoSizing { get => throw null; set { } }
        public global::TMPro.TMP_FontAsset font { get => throw null; set { } }
        public global::UnityEngine.Material fontMaterial { get => throw null; set { } }
        public virtual global::UnityEngine.Material fontSharedMaterial { get => throw null; set { } }
        public float fontSize { get => throw null; set { } }
        public float fontSizeMax { get => throw null; set { } }
        public float fontSizeMin { get => throw null; set { } }
        public global::TMPro.FontStyles fontStyle { get => throw null; set { } }
        public float lineSpacing { get => throw null; set { } }
        public virtual global::UnityEngine.Vector4 margin { get => throw null; set { } }
        public global::TMPro.TextOverflowModes overflowMode { get => throw null; set { } }
        public float paragraphSpacing { get => throw null; set { } }
        public global::UnityEngine.RectTransform rectTransform { get => throw null; }
        public bool richText { get => throw null; set { } }
        public global::TMPro.TMP_SpriteAsset spriteAsset { get => throw null; set { } }
        public virtual string text { get => throw null; set { } }
        public global::TMPro.TMP_TextInfo textInfo { get => throw null; }
        public global::UnityEngine.Transform transform { get => throw null; }
        public global::TMPro.VerticalAlignmentOptions verticalAlignment { get => throw null; set { } }
        public float wordSpacing { get => throw null; set { } }
        public virtual void ForceMeshUpdate(bool ignoreActiveState = default, bool forceTextReparsing = default) => throw null;
        public global::UnityEngine.Vector2 GetPreferredValues() => throw null;
        public global::UnityEngine.Vector2 GetPreferredValues(string text) => throw null;
        public void SetText(char[] sourceText, int start, int length) => throw null;
        public virtual void UpdateMeshPadding() => throw null;
        public virtual void UpdateVertexData(global::TMPro.TMP_VertexDataUpdateFlags flags) => throw null;
        protected TMP_Text() { }
    }
    public unsafe partial class TMP_TextElement {
        public float scale { get => throw null; set { } }
        protected TMP_TextElement() { }
    }
    public enum TMP_TextElementType : int {
        Character = 0,
        Sprite = 1,
    }
    public unsafe partial class TMP_TextElement_Legacy {
        protected TMP_TextElement_Legacy() { }
    }
    public unsafe partial class TMP_TextInfo {
        public int characterCount;
        public global::TMPro.TMP_CharacterInfo[] characterInfo;
        public global::TMPro.TMP_MeshInfo[] meshInfo;
        protected TMP_TextInfo() { }
    }
    public unsafe partial struct TMP_Vertex {
        public global::UnityEngine.Color32 color;
        public global::UnityEngine.Vector3 position;
        public global::UnityEngine.Vector4 uv;
        public global::UnityEngine.Vector2 uv2;
    }
    public enum TMP_VertexDataUpdateFlags : int {
        None = 0,
        Vertices = 1,
        Uv0 = 2,
        Uv2 = 4,
        Uv4 = 8,
        Colors32 = 16,
        All = 255,
    }
    public enum TextAlignmentOptions : int {
        TopLeft = 257,
        Top = 258,
        TopRight = 260,
        TopJustified = 264,
        TopFlush = 272,
        TopGeoAligned = 288,
        Left = 513,
        Center = 514,
        Right = 516,
        Justified = 520,
        Flush = 528,
        CenterGeoAligned = 544,
        BottomLeft = 1025,
        Bottom = 1026,
        BottomRight = 1028,
        BottomJustified = 1032,
        BottomFlush = 1040,
        BottomGeoAligned = 1056,
        BaselineLeft = 2049,
        Baseline = 2050,
        BaselineRight = 2052,
        BaselineJustified = 2056,
        BaselineFlush = 2064,
        BaselineGeoAligned = 2080,
        MidlineLeft = 4097,
        Midline = 4098,
        MidlineRight = 4100,
        MidlineJustified = 4104,
        MidlineFlush = 4112,
        MidlineGeoAligned = 4128,
        CaplineLeft = 8193,
        Capline = 8194,
        CaplineRight = 8196,
        CaplineJustified = 8200,
        CaplineFlush = 8208,
        CaplineGeoAligned = 8224,
        Converted = 65535,
    }
    public unsafe partial class TextMeshProUGUI : global::TMPro.TMP_Text {
        public global::UnityEngine.CanvasRenderer canvasRenderer { get => throw null; }
        protected TextMeshProUGUI() { }
    }
    public enum TextOverflowModes : int {
        Overflow = 0,
        Ellipsis = 1,
        Masking = 2,
        Truncate = 3,
        ScrollRect = 4,
        Page = 5,
        Linked = 6,
    }
    public enum VerticalAlignmentOptions : int {
        Top = 256,
        Middle = 512,
        Bottom = 1024,
        Baseline = 2048,
        Geometry = 4096,
        Capline = 8192,
    }
}
