using Mono.Cecil;
using System.Text.Json;

namespace Quartz.StubGen;

/// <summary>
/// Checks that every member a Harmony attribute or `nameof` names still exists in the
/// game, and records the verdict.
///
/// This is the one failure mode that costs the most and shows the least: Mono discards a
/// whole patched method at JIT time when a prefix references a game API that is gone, so
/// the feature dies silently — sometimes with the feature switched off — and the only
/// clue is a line in Player.log. Patch targets are named by string, so the compiler
/// cannot catch it and neither can the stub compile.
///
/// Resolution is by name only, since a string cannot say which overload was meant. That
/// makes this a check for "the member disappeared", not "the signature changed".
/// </summary>
static class PatchTargets {
    public sealed class Row {
        public string Type { get; set; }
        public string Member { get; set; }
        public bool Resolved { get; set; }
        public string Assembly { get; set; }
    }

    public static List<Row> Resolve(
        Dictionary<string, HashSet<string>> sourceTargets,
        IReadOnlyDictionary<string, AssemblyReq> stubs,
        IEnumerable<AssemblyDefinition> gameAssemblies) {

        // Index the real assemblies by type simple name and by full name, so a scan entry
        // matches however it was written in the attribute.
        Dictionary<string, List<TypeDefinition>> index = new(StringComparer.Ordinal);
        foreach(AssemblyDefinition assembly in gameAssemblies)
            foreach(ModuleDefinition module in assembly.Modules)
                foreach(TypeDefinition type in AllTypes(module)) {
                    Index(index, type.Name, type);
                    if(type.FullName != type.Name) Index(index, type.FullName, type);
                }

        List<Row> rows = new();
        foreach((string typeName, HashSet<string> members) in sourceTargets.OrderBy(k => k.Key, StringComparer.Ordinal)) {
            if(!index.TryGetValue(typeName, out List<TypeDefinition> candidates)) continue;
            foreach(string member in members.OrderBy(m => m, StringComparer.Ordinal)) {
                TypeDefinition owner = candidates.FirstOrDefault(c => HasMember(c, member));
                rows.Add(new Row {
                    Type = candidates[0].FullName,
                    Member = member,
                    Resolved = owner != null,
                    Assembly = (owner ?? candidates[0]).Module.Assembly.Name.Name,
                });
            }
        }
        return rows;
    }

    static void Index(Dictionary<string, List<TypeDefinition>> index, string key, TypeDefinition type) {
        if(!index.TryGetValue(key, out List<TypeDefinition> list)) index[key] = list = new List<TypeDefinition>();
        list.Add(type);
    }

    /// <summary>
    /// Walks the base chain too: Harmony resolves an inherited member fine, and a patch
    /// that names one is not broken.
    /// </summary>
    static bool HasMember(TypeDefinition type, string member) {
        for(TypeDefinition t = type; t != null; t = Safe(t.BaseType)) {
            if(t.Methods.Any(m => m.Name == member)) return true;
            if(t.Fields.Any(f => f.Name == member)) return true;
            if(t.Properties.Any(p => p.Name == member)) return true;
            if(t.Events.Any(e => e.Name == member)) return true;
            if(t.NestedTypes.Any(n => n.Name == member)) return true;
        }
        return false;
    }

    static TypeDefinition Safe(TypeReference tr) {
        try { return tr?.Resolve(); } catch { return null; }
    }

    static IEnumerable<TypeDefinition> AllTypes(ModuleDefinition module) {
        foreach(TypeDefinition t in module.Types)
            foreach(TypeDefinition n in Nested(t))
                yield return n;
    }

    static IEnumerable<TypeDefinition> Nested(TypeDefinition t) {
        yield return t;
        foreach(TypeDefinition c in t.NestedTypes)
            foreach(TypeDefinition n in Nested(c))
                yield return n;
    }

    public static string Render(List<Row> rows) {
        var model = new {
            comment = "Generated by tools/StubGen. Every game member named by a Harmony "
                + "attribute or nameof(), checked against the installed game. An entry with "
                + "resolved=false is a patch whose target no longer exists — Mono will drop "
                + "the whole patched method at JIT time. scripts/check_conventions.py fails on one.",
            unresolved = rows.Count(r => !r.Resolved),
            targets = rows.Select(r => new {
                type = r.Type,
                member = r.Member,
                resolved = r.Resolved,
                assembly = r.Assembly,
            }).ToArray(),
        };
        return JsonSerializer.Serialize(model, new JsonSerializerOptions { WriteIndented = true }) + "\n";
    }
}
