// <auto-generated>
//   Compile-only stand-in for "UnityEngine.UI", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine.EventSystems {
    public abstract unsafe partial class AbstractEventData {
        protected AbstractEventData() { }
    }
    public unsafe partial class BaseEventData : global::UnityEngine.EventSystems.AbstractEventData {
        protected BaseEventData() { }
    }
    public abstract unsafe partial class BaseInputModule : global::UnityEngine.EventSystems.UIBehaviour {
        protected BaseInputModule() { }
    }
    public abstract unsafe partial class BaseRaycaster : global::UnityEngine.EventSystems.UIBehaviour {
        protected BaseRaycaster() { }
    }
    public unsafe partial class EventSystem : global::UnityEngine.EventSystems.UIBehaviour {
        public static global::UnityEngine.EventSystems.EventSystem current { get => throw null; set { } }
        public global::UnityEngine.GameObject currentSelectedGameObject { get => throw null; }
        protected EventSystem() { }
    }
    public unsafe partial class EventTrigger : global::UnityEngine.MonoBehaviour, global::UnityEngine.EventSystems.IPointerDownHandler, global::UnityEngine.EventSystems.IPointerUpHandler, global::UnityEngine.EventSystems.IPointerClickHandler, global::UnityEngine.EventSystems.IBeginDragHandler, global::UnityEngine.EventSystems.IDragHandler, global::UnityEngine.EventSystems.IEndDragHandler {
        public global::System.Collections.Generic.List<global::UnityEngine.EventSystems.EventTrigger.Entry> triggers { get => throw null; set { } }
        protected EventTrigger() { }
        void global::UnityEngine.EventSystems.IBeginDragHandler.OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IDragHandler.OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IEndDragHandler.OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerDownHandler.OnPointerDown(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerUpHandler.OnPointerUp(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public unsafe partial class TriggerEvent : global::UnityEngine.Events.UnityEvent<global::UnityEngine.EventSystems.BaseEventData> {
            protected TriggerEvent() { }
        }
        public unsafe partial class Entry {
            public global::UnityEngine.EventSystems.EventTrigger.TriggerEvent callback;
            public global::UnityEngine.EventSystems.EventTriggerType eventID;
            public Entry() => throw null;
        }
    }
    public enum EventTriggerType : int {
        PointerEnter = 0,
        PointerExit = 1,
        PointerDown = 2,
        PointerUp = 3,
        PointerClick = 4,
        Drag = 5,
        Drop = 6,
        Scroll = 7,
        UpdateSelected = 8,
        Select = 9,
        Deselect = 10,
        Move = 11,
        InitializePotentialDrag = 12,
        BeginDrag = 13,
        EndDrag = 14,
        Submit = 15,
        Cancel = 16,
    }
    public unsafe partial interface IBeginDragHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface ICancelHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IDeselectHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IDragHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface IDropHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IEndDragHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface IEventSystemHandler {
    }
    public unsafe partial interface IInitializePotentialDragHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IMoveHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IPointerClickHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnPointerClick(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface IPointerDownHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnPointerDown(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface IPointerEnterHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IPointerExitHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IPointerUpHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
        void OnPointerUp(global::UnityEngine.EventSystems.PointerEventData eventData);
    }
    public unsafe partial interface IScrollHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface ISelectHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface ISubmitHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial interface IUpdateSelectedHandler : global::UnityEngine.EventSystems.IEventSystemHandler {
    }
    public unsafe partial class PointerEventData : global::UnityEngine.EventSystems.BaseEventData {
        public global::UnityEngine.EventSystems.PointerEventData.InputButton button { get => throw null; set { } }
        public bool dragging { get => throw null; set { } }
        public global::UnityEngine.EventSystems.RaycastResult pointerCurrentRaycast { get => throw null; set { } }
        public global::UnityEngine.Vector2 position { get => throw null; set { } }
        public global::UnityEngine.Camera pressEventCamera { get => throw null; }
        protected PointerEventData() { }
        public enum InputButton : int {
            Left = 0,
            Right = 1,
            Middle = 2,
        }
        public enum FramePressState : int {
            Pressed = 0,
            Released = 1,
            PressedAndReleased = 2,
            NotChanged = 3,
        }
    }
    public abstract unsafe partial class PointerInputModule : global::UnityEngine.EventSystems.BaseInputModule {
        public const int kFakeTouchesId = 0;
        public const int kMouseLeftId = 1;
        public const int kMouseMiddleId = 2;
        public const int kMouseRightId = 3;
        protected PointerInputModule() { }
    }
    public unsafe partial struct RaycastResult {
        public int depth;
        public int displayIndex;
        public float distance;
        public global::UnityEngine.UIElements.UIDocument document;
        public global::UnityEngine.UIElements.VisualElement element;
        public float index;
        private global::UnityEngine.GameObject m_GameObject;
        public global::UnityEngine.EventSystems.BaseRaycaster module;
        public global::UnityEngine.Vector3 origin;
        public global::UnityEngine.Vector2 screenPosition;
        public int sortingGroupID;
        public int sortingGroupOrder;
        public int sortingLayer;
        public int sortingOrder;
        public global::UnityEngine.Vector3 worldNormal;
        public global::UnityEngine.Vector3 worldPosition;
        public global::UnityEngine.GameObject gameObject { get => throw null; set { } }
    }
    public unsafe partial class StandaloneInputModule : global::UnityEngine.EventSystems.PointerInputModule {
        protected StandaloneInputModule() { }
        public enum InputMode : int {
            Mouse = 0,
            Buttons = 1,
        }
    }
    public abstract unsafe partial class UIBehaviour : global::UnityEngine.MonoBehaviour {
        protected UIBehaviour() { }
    }
}
namespace UnityEngine.UI {
    public abstract unsafe partial class BaseMeshEffect : global::UnityEngine.EventSystems.UIBehaviour {
        protected BaseMeshEffect() { }
    }
    public unsafe partial class Button : global::UnityEngine.UI.Selectable, global::UnityEngine.EventSystems.IPointerClickHandler {
        public global::UnityEngine.UI.Button.ButtonClickedEvent onClick { get => throw null; set { } }
        protected Button() { }
        void global::UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public unsafe partial class ButtonClickedEvent : global::UnityEngine.Events.UnityEvent {
            protected ButtonClickedEvent() { }
        }
    }
    public unsafe partial class CanvasScaler : global::UnityEngine.EventSystems.UIBehaviour {
        public float matchWidthOrHeight { get => throw null; set { } }
        public global::UnityEngine.Vector2 referenceResolution { get => throw null; set { } }
        public global::UnityEngine.UI.CanvasScaler.ScreenMatchMode screenMatchMode { get => throw null; set { } }
        public global::UnityEngine.UI.CanvasScaler.ScaleMode uiScaleMode { get => throw null; set { } }
        protected CanvasScaler() { }
        public enum ScaleMode : int {
            ConstantPixelSize = 0,
            ScaleWithScreenSize = 1,
            ConstantPhysicalSize = 2,
        }
        public enum ScreenMatchMode : int {
            MatchWidthOrHeight = 0,
            Expand = 1,
            Shrink = 2,
        }
        public enum Unit : int {
            Centimeters = 0,
            Millimeters = 1,
            Inches = 2,
            Points = 3,
            Picas = 4,
        }
    }
    public unsafe partial class ContentSizeFitter : global::UnityEngine.EventSystems.UIBehaviour {
        public global::UnityEngine.UI.ContentSizeFitter.FitMode horizontalFit { get => throw null; set { } }
        public global::UnityEngine.UI.ContentSizeFitter.FitMode verticalFit { get => throw null; set { } }
        protected ContentSizeFitter() { }
        public enum FitMode : int {
            Unconstrained = 0,
            MinSize = 1,
            PreferredSize = 2,
        }
    }
    public abstract unsafe partial class Graphic : global::UnityEngine.EventSystems.UIBehaviour {
        public global::UnityEngine.CanvasRenderer canvasRenderer { get => throw null; }
        public virtual global::UnityEngine.Color color { get => throw null; set { } }
        public virtual global::UnityEngine.Texture mainTexture { get => throw null; }
        public virtual bool raycastTarget { get => throw null; set { } }
        public virtual global::UnityEngine.RectTransform rectTransform { get => throw null; }
        protected Graphic() => throw null;
        protected virtual void OnPopulateMesh(global::UnityEngine.UI.VertexHelper vh) => throw null;
        protected virtual void OnRectTransformDimensionsChange() => throw null;
        public virtual void SetVerticesDirty() => throw null;
    }
    public unsafe partial class GraphicRaycaster : global::UnityEngine.EventSystems.BaseRaycaster {
        protected GraphicRaycaster() { }
        public enum BlockingObjects : int {
            None = 0,
            TwoD = 1,
            ThreeD = 2,
            All = 3,
        }
    }
    public unsafe partial class HorizontalLayoutGroup : global::UnityEngine.UI.HorizontalOrVerticalLayoutGroup {
        protected HorizontalLayoutGroup() { }
    }
    public abstract unsafe partial class HorizontalOrVerticalLayoutGroup : global::UnityEngine.UI.LayoutGroup {
        public bool childControlHeight { get => throw null; set { } }
        public bool childControlWidth { get => throw null; set { } }
        public bool childForceExpandHeight { get => throw null; set { } }
        public bool childForceExpandWidth { get => throw null; set { } }
        public float spacing { get => throw null; set { } }
        protected HorizontalOrVerticalLayoutGroup() { }
    }
    public unsafe partial interface ICanvasElement {
    }
    public unsafe partial interface IClippable {
    }
    public unsafe partial interface IClipper {
    }
    public unsafe partial interface ILayoutController {
    }
    public unsafe partial interface ILayoutElement {
    }
    public unsafe partial interface ILayoutGroup : global::UnityEngine.UI.ILayoutController {
    }
    public unsafe partial interface ILayoutIgnorer {
    }
    public unsafe partial interface ILayoutSelfController : global::UnityEngine.UI.ILayoutController {
    }
    public unsafe partial interface IMaskable {
    }
    public unsafe partial interface IMaterialModifier {
    }
    public unsafe partial interface IMeshModifier {
    }
    public unsafe partial class Image : global::UnityEngine.UI.MaskableGraphic {
        public float fillAmount { get => throw null; set { } }
        public global::UnityEngine.UI.Image.FillMethod fillMethod { get => throw null; set { } }
        public int fillOrigin { get => throw null; set { } }
        public float pixelsPerUnitMultiplier { get => throw null; set { } }
        public bool preserveAspect { get => throw null; set { } }
        public global::UnityEngine.Sprite sprite { get => throw null; set { } }
        public global::UnityEngine.UI.Image.Type type { get => throw null; set { } }
        protected Image() { }
        public enum Type : int {
            Simple = 0,
            Sliced = 1,
            Tiled = 2,
            Filled = 3,
        }
        public enum FillMethod : int {
            Horizontal = 0,
            Vertical = 1,
            Radial90 = 2,
            Radial180 = 3,
            Radial360 = 4,
        }
        public enum OriginHorizontal : int {
            Left = 0,
            Right = 1,
        }
        public enum OriginVertical : int {
            Bottom = 0,
            Top = 1,
        }
        public enum Origin90 : int {
            BottomLeft = 0,
            TopLeft = 1,
            TopRight = 2,
            BottomRight = 3,
        }
        public enum Origin180 : int {
            Bottom = 0,
            Left = 1,
            Top = 2,
            Right = 3,
        }
        public enum Origin360 : int {
            Bottom = 0,
            Right = 1,
            Top = 2,
            Left = 3,
        }
    }
    public unsafe partial class InputField : global::UnityEngine.UI.Selectable, global::UnityEngine.EventSystems.IBeginDragHandler, global::UnityEngine.EventSystems.IDragHandler, global::UnityEngine.EventSystems.IEndDragHandler, global::UnityEngine.EventSystems.IPointerClickHandler {
        public global::UnityEngine.Color caretColor { get => throw null; set { } }
        public global::UnityEngine.UI.InputField.EndEditEvent onEndEdit { get => throw null; set { } }
        public global::UnityEngine.UI.InputField.OnChangeEvent onValueChanged { get => throw null; set { } }
        public global::UnityEngine.UI.Graphic placeholder { get => throw null; set { } }
        public string text { get => throw null; set { } }
        public global::UnityEngine.UI.Text textComponent { get => throw null; set { } }
        public void ActivateInputField() => throw null;
        protected InputField() { }
        void global::UnityEngine.EventSystems.IBeginDragHandler.OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IDragHandler.OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IEndDragHandler.OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public enum ContentType : int {
            Standard = 0,
            Autocorrected = 1,
            IntegerNumber = 2,
            DecimalNumber = 3,
            Alphanumeric = 4,
            Name = 5,
            EmailAddress = 6,
            Password = 7,
            Pin = 8,
            Custom = 9,
        }
        public enum InputType : int {
            Standard = 0,
            AutoCorrect = 1,
            Password = 2,
        }
        public enum CharacterValidation : int {
            None = 0,
            Integer = 1,
            Decimal = 2,
            Alphanumeric = 3,
            Name = 4,
            EmailAddress = 5,
        }
        public enum LineType : int {
            SingleLine = 0,
            MultiLineSubmit = 1,
            MultiLineNewline = 2,
        }
        public unsafe partial class EndEditEvent : global::UnityEngine.Events.UnityEvent<string> {
            protected EndEditEvent() { }
        }
        public unsafe partial class OnChangeEvent : global::UnityEngine.Events.UnityEvent<string> {
            protected OnChangeEvent() { }
        }
        public enum EditState : int {
            Continue = 0,
            Finish = 1,
        }
    }
    public unsafe partial class LayoutElement : global::UnityEngine.EventSystems.UIBehaviour {
        public virtual float flexibleHeight { get => throw null; set { } }
        public virtual float flexibleWidth { get => throw null; set { } }
        public virtual bool ignoreLayout { get => throw null; set { } }
        public virtual float minHeight { get => throw null; set { } }
        public virtual float minWidth { get => throw null; set { } }
        public virtual float preferredHeight { get => throw null; set { } }
        public virtual float preferredWidth { get => throw null; set { } }
        protected LayoutElement() { }
    }
    public abstract unsafe partial class LayoutGroup : global::UnityEngine.EventSystems.UIBehaviour {
        public global::UnityEngine.TextAnchor childAlignment { get => throw null; set { } }
        public global::UnityEngine.RectOffset padding { get => throw null; set { } }
        protected LayoutGroup() { }
    }
    public unsafe partial class LayoutRebuilder {
        public static void ForceRebuildLayoutImmediate(global::UnityEngine.RectTransform layoutRoot) => throw null;
        public static void MarkLayoutForRebuild(global::UnityEngine.RectTransform rect) => throw null;
        protected LayoutRebuilder() { }
    }
    public static unsafe partial class LayoutUtility {
        public static float GetMinHeight(global::UnityEngine.RectTransform rect) => throw null;
        public static float GetPreferredWidth(global::UnityEngine.RectTransform rect) => throw null;
    }
    public unsafe partial class Mask : global::UnityEngine.EventSystems.UIBehaviour {
        public bool showMaskGraphic { get => throw null; set { } }
        protected Mask() { }
    }
    public abstract unsafe partial class MaskableGraphic : global::UnityEngine.UI.Graphic {
        protected MaskableGraphic() => throw null;
    }
    public unsafe partial class Outline : global::UnityEngine.UI.Shadow {
        protected Outline() { }
    }
    public unsafe partial class RawImage : global::UnityEngine.UI.MaskableGraphic {
        public global::UnityEngine.Texture texture { get => throw null; set { } }
        public global::UnityEngine.Rect uvRect { get => throw null; set { } }
        protected RawImage() => throw null;
    }
    public unsafe partial class RectMask2D : global::UnityEngine.EventSystems.UIBehaviour {
        protected RectMask2D() { }
    }
    public unsafe partial class ScrollRect : global::UnityEngine.EventSystems.UIBehaviour, global::UnityEngine.EventSystems.IBeginDragHandler, global::UnityEngine.EventSystems.IEndDragHandler, global::UnityEngine.EventSystems.IDragHandler {
        public global::UnityEngine.RectTransform content { get => throw null; set { } }
        public bool horizontal { get => throw null; set { } }
        public bool inertia { get => throw null; set { } }
        public global::UnityEngine.UI.ScrollRect.MovementType movementType { get => throw null; set { } }
        public float scrollSensitivity { get => throw null; set { } }
        public bool vertical { get => throw null; set { } }
        public global::UnityEngine.RectTransform viewport { get => throw null; set { } }
        public virtual void OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public virtual void OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public virtual void OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public virtual void OnInitializePotentialDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        protected ScrollRect() { }
        void global::UnityEngine.EventSystems.IBeginDragHandler.OnBeginDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IDragHandler.OnDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IEndDragHandler.OnEndDrag(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public enum MovementType : int {
            Unrestricted = 0,
            Elastic = 1,
            Clamped = 2,
        }
        public enum ScrollbarVisibility : int {
            Permanent = 0,
            AutoHide = 1,
            AutoHideAndExpandViewport = 2,
        }
    }
    public unsafe partial class Selectable : global::UnityEngine.EventSystems.UIBehaviour, global::UnityEngine.EventSystems.IPointerDownHandler, global::UnityEngine.EventSystems.IPointerUpHandler {
        public global::UnityEngine.UI.Image image { get => throw null; set { } }
        public bool interactable { get => throw null; set { } }
        public global::UnityEngine.UI.SpriteState spriteState { get => throw null; set { } }
        public global::UnityEngine.UI.Graphic targetGraphic { get => throw null; set { } }
        public global::UnityEngine.UI.Selectable.Transition transition { get => throw null; set { } }
        public virtual void Select() => throw null;
        protected Selectable() { }
        void global::UnityEngine.EventSystems.IPointerDownHandler.OnPointerDown(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        void global::UnityEngine.EventSystems.IPointerUpHandler.OnPointerUp(global::UnityEngine.EventSystems.PointerEventData eventData) => throw null;
        public enum Transition : int {
            None = 0,
            ColorTint = 1,
            SpriteSwap = 2,
            Animation = 3,
        }
        public enum SelectionState : int {
            Normal = 0,
            Highlighted = 1,
            Pressed = 2,
            Selected = 3,
            Disabled = 4,
        }
    }
    public unsafe partial class Shadow : global::UnityEngine.UI.BaseMeshEffect {
        public global::UnityEngine.Color effectColor { get => throw null; set { } }
        protected Shadow() { }
    }
    public unsafe partial struct SpriteState : global::System.IEquatable<global::UnityEngine.UI.SpriteState> {
        private global::UnityEngine.Sprite m_DisabledSprite;
        private global::UnityEngine.Sprite m_HighlightedSprite;
        private global::UnityEngine.Sprite m_PressedSprite;
        private global::UnityEngine.Sprite m_SelectedSprite;
        public global::UnityEngine.Sprite disabledSprite { get => throw null; set { } }
        public global::UnityEngine.Sprite highlightedSprite { get => throw null; set { } }
        public global::UnityEngine.Sprite pressedSprite { get => throw null; set { } }
        public global::UnityEngine.Sprite selectedSprite { get => throw null; set { } }
        bool global::System.IEquatable<global::UnityEngine.UI.SpriteState>.Equals(global::UnityEngine.UI.SpriteState other) => throw null;
    }
    public unsafe partial class Text : global::UnityEngine.UI.MaskableGraphic {
        public global::UnityEngine.TextAnchor alignment { get => throw null; set { } }
        public int fontSize { get => throw null; set { } }
        public global::UnityEngine.FontStyle fontStyle { get => throw null; set { } }
        public global::UnityEngine.HorizontalWrapMode horizontalOverflow { get => throw null; set { } }
        public float lineSpacing { get => throw null; set { } }
        public bool resizeTextForBestFit { get => throw null; set { } }
        public int resizeTextMaxSize { get => throw null; set { } }
        public bool supportRichText { get => throw null; set { } }
        public virtual string text { get => throw null; set { } }
        public global::UnityEngine.VerticalWrapMode verticalOverflow { get => throw null; set { } }
        protected Text() { }
    }
    public unsafe partial class VertexHelper : global::System.IDisposable {
        public int currentVertCount { get => throw null; }
        public void AddTriangle(int idx0, int idx1, int idx2) => throw null;
        public void AddVert(global::UnityEngine.UIVertex v) => throw null;
        public void AddVert(global::UnityEngine.Vector3 position, global::UnityEngine.Color32 color, global::UnityEngine.Vector4 uv0) => throw null;
        public void Clear() => throw null;
        protected VertexHelper() { }
        void global::System.IDisposable.Dispose() => throw null;
    }
    public unsafe partial class VerticalLayoutGroup : global::UnityEngine.UI.HorizontalOrVerticalLayoutGroup {
        protected VerticalLayoutGroup() { }
    }
}
