<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ModuleId>discord</ModuleId>
		<AssemblyName>Quartz.Module.Discord</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Lang\*.json" />
		<EmbeddedResource Include="voice-natives.json" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.IO.Compression.FileSystem"><HintPath>$(ManagedDir)/System.IO.Compression.FileSystem.dll</HintPath></Reference>
	</ItemGroup>

</Project>
