// <auto-generated>
//   Compile-only stand-in for "UnityEngine.AudioModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace Unity.Audio {
    public unsafe partial struct Handle : global::Unity.Audio.IHandle<global::Unity.Audio.Handle> {
        public int Version;
        private global::System.IntPtr m_Node;
        bool global::System.IEquatable<global::Unity.Audio.Handle>.Equals(global::Unity.Audio.Handle other) => throw null;
        bool global::Unity.Audio.IValidatable.Valid { get => throw null; }
    }
    public unsafe partial interface IHandle<HandleType> : global::Unity.Audio.IValidatable, global::System.IEquatable<HandleType> where HandleType : struct, global::Unity.Audio.IHandle<HandleType> {
    }
    public unsafe partial interface IValidatable {
        bool Valid { get; }
    }
}
namespace UnityEngine {
    public unsafe partial class AudioBehaviour : global::UnityEngine.Behaviour {
        protected AudioBehaviour() { }
    }
    public sealed unsafe partial class AudioClip : global::UnityEngine.Audio.AudioResource {
        public int channels { get => throw null; }
        public int frequency { get => throw null; }
        public float length { get => throw null; }
        public global::UnityEngine.AudioDataLoadState loadState { get => throw null; }
        public int samples { get => throw null; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool stream) => throw null;
        public bool GetData(float[] data, int offsetSamples) => throw null;
        public bool LoadAudioData() => throw null;
        public bool SetData(float[] data, int offsetSamples) => throw null;
        private AudioClip() { }
    }
    public enum AudioDataLoadState : int {
        Unloaded = 0,
        Loading = 1,
        Loaded = 2,
        Failed = 3,
    }
    public sealed unsafe partial class AudioListener : global::UnityEngine.AudioBehaviour {
        public static bool pause { get => throw null; set { } }
        private AudioListener() { }
    }
    public sealed unsafe partial class AudioSettings {
        public static double dspTime { get => throw null; }
        public static int outputSampleRate { get => throw null; set { } }
        private AudioSettings() { }
    }
    public sealed unsafe partial class AudioSource : global::UnityEngine.AudioBehaviour {
        public global::UnityEngine.AudioClip clip { get => throw null; set { } }
        public bool ignoreListenerPause { get => throw null; set { } }
        public bool isPlaying { get => throw null; }
        public bool loop { get => throw null; set { } }
        public bool mute { get => throw null; set { } }
        public global::UnityEngine.Audio.AudioMixerGroup outputAudioMixerGroup { get => throw null; set { } }
        public float pitch { get => throw null; set { } }
        public bool playOnAwake { get => throw null; set { } }
        public int priority { get => throw null; set { } }
        public float spatialBlend { get => throw null; set { } }
        public float time { get => throw null; set { } }
        public int timeSamples { get => throw null; set { } }
        public float volume { get => throw null; set { } }
        public void Pause() => throw null;
        public void Play() => throw null;
        public void PlayScheduled(double time) => throw null;
        public void SetScheduledEndTime(double time) => throw null;
        public void Stop() => throw null;
        public void UnPause() => throw null;
        private AudioSource() { }
    }
}
namespace UnityEngine.Audio {
    public unsafe partial class AudioMixerGroup : global::UnityEngine.Object {
        protected AudioMixerGroup() { }
    }
    public abstract unsafe partial class AudioResource : global::UnityEngine.Object {
        protected AudioResource() { }
    }
    public unsafe partial struct GeneratorInstance : global::System.IEquatable<global::UnityEngine.Audio.GeneratorInstance> {
        private readonly global::UnityEngine.Audio.ProcessorInstance m_ProcessorInstance;
        bool global::System.IEquatable<global::UnityEngine.Audio.GeneratorInstance>.Equals(global::UnityEngine.Audio.GeneratorInstance other) => throw null;
        public unsafe partial interface ICapabilities {
        }
    }
    public unsafe partial interface IAudioGenerator : global::UnityEngine.Audio.GeneratorInstance.ICapabilities {
    }
    public unsafe partial struct ProcessorHeader {
        private global::System.IntPtr ControlReflectionData;
        private global::Unity.Audio.Handle DualThreadHandle;
        private global::System.IntPtr NativeControlFunction;
        private global::System.IntPtr NativeProcessorFunction;
        private global::System.IntPtr ProcessorReflectionData;
        private void* m_Control;
    }
    public readonly unsafe partial struct ProcessorInstance : global::System.IEquatable<global::UnityEngine.Audio.ProcessorInstance> {
        private readonly global::Unity.Audio.Handle Handle;
        private readonly global::UnityEngine.Audio.ProcessorHeader* Header;
        bool global::System.IEquatable<global::UnityEngine.Audio.ProcessorInstance>.Equals(global::UnityEngine.Audio.ProcessorInstance other) => throw null;
        public enum MessageStatus : int {
        }
        public enum UpdateSetting : int {
            Default = 0,
            NeverUpdate = 1,
            UpdateIfDataIsAvailable = 2,
            UpdateAlways = 3,
        }
        public enum Response : int {
            Unhandled = 0,
            Handled = 1,
        }
    }
}
