namespace Quartz.Interop;
public static class ImportKeys {
    public const string UiHiderPlayingProfile = "uihider.playing";
    public const string UiHiderRecordingProfile = "uihider.recording";
    public const string UiHiderShortcut = "uihider.shortcut";
    public const string UiHiderShortcutKey = "uihider.shortcutKey";
    public const string UiHiderRecordingMode = "uihider.recordingMode";
    public const string UiHiderUseShortcut = "uihider.useShortcut";
    public const string UiHiderEnabled = "uihider.enabled";
    public const string RestrictionAllowedMask = "restriction.allowedMask";
    public const string TweaksBlockScroll = "tweaks.blockScroll";
    public const string KeyLimiterEnabled = "keylimiter.enabled";
    public const string KeyLimiterAllowedKeys = "keylimiter.allowedKeys";
    public const string ChatterEnabled = "chatterblocker.enabled";
    public const string ChatterThresholdMs = "chatterblocker.thresholdMs";
    public const string KeyViewerPayload = "keyviewer.payload";
    public const string KeyViewerMode = "keyviewer.mode";
    public const string KeyViewerParts = "keyviewer.parts";
    public const string ComboEnabled = "combo.enabled";
    public const string ComboCountAuto = "combo.countAuto";
    public const string ComboColorMax = "combo.colorMax";
    public const string ComboColorLow = "combo.colorLow";
    public const string ComboColorHigh = "combo.colorHigh";
    public const string JudgementEnabled = "judgement.enabled";
    public const string JudgementOffsetY = "judgement.offsetY";
    public const string ProgressBarEnabled = "progressbar.enabled";
    public const string ProgressBarFill = "progressbar.fill";
    public const string ProgressBarBack = "progressbar.back";
    public const string ProgressBarBorder = "progressbar.border";
}
