// <auto-generated>
//   Compile-only stand-in for "Newtonsoft.Json", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace Newtonsoft.Json {
    public enum DateParseHandling : int {
        None = 0,
        DateTime = 1,
        DateTimeOffset = 2,
    }
    public enum Formatting : int {
        None = 0,
        Indented = 1,
    }
    public unsafe partial interface IJsonLineInfo {
    }
    public static unsafe partial class JsonConvert {
        public static void PopulateObject(string value, object target) => throw null;
        public static string SerializeObject(object value) => throw null;
        public static string SerializeObject(object value, global::Newtonsoft.Json.Formatting formatting) => throw null;
    }
    public abstract unsafe partial class JsonConverter {
        protected JsonConverter() { }
    }
    public unsafe partial class JsonException : global::System.Exception {
        protected JsonException() { }
    }
    public abstract unsafe partial class JsonReader : global::System.IDisposable {
        public global::Newtonsoft.Json.DateParseHandling DateParseHandling { get => throw null; set { } }
        public global::System.Nullable<int> MaxDepth { get => throw null; set { } }
        public virtual global::Newtonsoft.Json.JsonToken TokenType { get => throw null; }
        public virtual object Value { get => throw null; }
        public virtual bool Read() => throw null;
        public void Skip() => throw null;
        protected JsonReader() { }
        void global::System.IDisposable.Dispose() => throw null;
    }
    public unsafe partial class JsonTextReader : global::Newtonsoft.Json.JsonReader {
        public JsonTextReader(global::System.IO.TextReader reader) => throw null;
        protected JsonTextReader() { }
    }
    public enum JsonToken : int {
        None = 0,
        StartObject = 1,
        StartArray = 2,
        StartConstructor = 3,
        PropertyName = 4,
        Comment = 5,
        Raw = 6,
        Integer = 7,
        Float = 8,
        String = 9,
        Boolean = 10,
        Null = 11,
        Undefined = 12,
        EndObject = 13,
        EndArray = 14,
        EndConstructor = 15,
        Date = 16,
        Bytes = 17,
    }
}
namespace Newtonsoft.Json.Linq {
    public static unsafe partial class Extensions {
        public static U Value<U>(this global::System.Collections.Generic.IEnumerable<global::Newtonsoft.Json.Linq.JToken> value) => throw null;
    }
    public unsafe partial interface IJEnumerable<T> : global::System.Collections.Generic.IEnumerable<T>, global::System.Collections.IEnumerable where T : global::Newtonsoft.Json.Linq.JToken {
    }
    public unsafe partial class JArray : global::Newtonsoft.Json.Linq.JContainer {
        public virtual global::Newtonsoft.Json.Linq.JToken this[int index] { get => throw null; set { } }
        public JArray() => throw null;
        public JArray(params object[] content) => throw null;
        public JArray(object content) => throw null;
        public virtual void Add(global::Newtonsoft.Json.Linq.JToken item) => throw null;
        public virtual global::System.Collections.Generic.IEnumerator<global::Newtonsoft.Json.Linq.JToken> GetEnumerator() => throw null;
        public static global::Newtonsoft.Json.Linq.JArray Parse(string json) => throw null;
        public virtual void RemoveAt(int index) => throw null;
    }
    public abstract unsafe partial class JContainer : global::Newtonsoft.Json.Linq.JToken, global::System.Collections.Generic.IList<global::Newtonsoft.Json.Linq.JToken>, global::System.Collections.IList {
        public virtual int Count { get => throw null; }
        protected JContainer() { }
        void global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.Add(global::Newtonsoft.Json.Linq.JToken item) => throw null;
        void global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.Clear() => throw null;
        bool global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.Contains(global::Newtonsoft.Json.Linq.JToken item) => throw null;
        void global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.CopyTo(global::Newtonsoft.Json.Linq.JToken[] array, int arrayIndex) => throw null;
        bool global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.Remove(global::Newtonsoft.Json.Linq.JToken item) => throw null;
        global::System.Collections.Generic.IEnumerator<global::Newtonsoft.Json.Linq.JToken> global::System.Collections.Generic.IEnumerable<global::Newtonsoft.Json.Linq.JToken>.GetEnumerator() => throw null;
        int global::System.Collections.Generic.IList<global::Newtonsoft.Json.Linq.JToken>.IndexOf(global::Newtonsoft.Json.Linq.JToken item) => throw null;
        void global::System.Collections.Generic.IList<global::Newtonsoft.Json.Linq.JToken>.Insert(int index, global::Newtonsoft.Json.Linq.JToken item) => throw null;
        void global::System.Collections.Generic.IList<global::Newtonsoft.Json.Linq.JToken>.RemoveAt(int index) => throw null;
        void global::System.Collections.ICollection.CopyTo(global::System.Array array, int index) => throw null;
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => throw null;
        int global::System.Collections.IList.Add(object value) => throw null;
        void global::System.Collections.IList.Clear() => throw null;
        bool global::System.Collections.IList.Contains(object value) => throw null;
        int global::System.Collections.IList.IndexOf(object value) => throw null;
        void global::System.Collections.IList.Insert(int index, object value) => throw null;
        void global::System.Collections.IList.RemoveAt(int index) => throw null;
        void global::System.Collections.IList.Remove(object value) => throw null;
        int global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.Count { get => throw null; }
        bool global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken>.IsReadOnly { get => throw null; }
        global::Newtonsoft.Json.Linq.JToken global::System.Collections.Generic.IList<global::Newtonsoft.Json.Linq.JToken>.this[int index] { get => throw null; set { } }
        int global::System.Collections.ICollection.Count { get => throw null; }
        bool global::System.Collections.ICollection.IsSynchronized { get => throw null; }
        object global::System.Collections.ICollection.SyncRoot { get => throw null; }
        bool global::System.Collections.IList.IsFixedSize { get => throw null; }
        bool global::System.Collections.IList.IsReadOnly { get => throw null; }
        object global::System.Collections.IList.this[int index] { get => throw null; set { } }
    }
    public unsafe partial class JObject : global::Newtonsoft.Json.Linq.JContainer, global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken> {
        public virtual global::Newtonsoft.Json.Linq.JToken this[string propertyName] { get => throw null; set { } }
        public JObject() => throw null;
        public virtual global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>> GetEnumerator() => throw null;
        public static global::Newtonsoft.Json.Linq.JObject Load(global::Newtonsoft.Json.JsonReader reader) => throw null;
        public static global::Newtonsoft.Json.Linq.JObject Parse(string json) => throw null;
        public global::System.Collections.Generic.IEnumerable<global::Newtonsoft.Json.Linq.JProperty> Properties() => throw null;
        public virtual bool Remove(string propertyName) => throw null;
        public virtual bool TryGetValue(string propertyName, out global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public bool TryGetValue(string propertyName, global::System.StringComparison comparison, out global::Newtonsoft.Json.Linq.JToken value) => throw null;
        void global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.Add(global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken> item) => throw null;
        void global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.Clear() => throw null;
        bool global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.Contains(global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken> item) => throw null;
        void global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.CopyTo(global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>[] array, int arrayIndex) => throw null;
        bool global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.Remove(global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken> item) => throw null;
        void global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.Add(string key, global::Newtonsoft.Json.Linq.JToken value) => throw null;
        bool global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.ContainsKey(string key) => throw null;
        bool global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.Remove(string key) => throw null;
        bool global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.TryGetValue(string key, out global::Newtonsoft.Json.Linq.JToken value) => throw null;
        global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.GetEnumerator() => throw null;
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => throw null;
        int global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.Count { get => throw null; }
        bool global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<string, global::Newtonsoft.Json.Linq.JToken>>.IsReadOnly { get => throw null; }
        global::System.Collections.Generic.ICollection<string> global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.Keys { get => throw null; }
        global::System.Collections.Generic.ICollection<global::Newtonsoft.Json.Linq.JToken> global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.Values { get => throw null; }
        global::Newtonsoft.Json.Linq.JToken global::System.Collections.Generic.IDictionary<string, global::Newtonsoft.Json.Linq.JToken>.this[string key] { get => throw null; set { } }
    }
    public unsafe partial class JProperty : global::Newtonsoft.Json.Linq.JContainer {
        public string Name { get => throw null; }
        public global::Newtonsoft.Json.Linq.JToken Value { get => throw null; set { } }
        protected JProperty() { }
    }
    public abstract unsafe partial class JToken : global::System.Collections.Generic.IEnumerable<global::Newtonsoft.Json.Linq.JToken> {
        public virtual global::Newtonsoft.Json.Linq.JToken this[object key] { get => throw null; set { } }
        public global::Newtonsoft.Json.Linq.JContainer Parent { get => throw null; }
        public virtual global::Newtonsoft.Json.Linq.JTokenType Type { get => throw null; }
        public global::Newtonsoft.Json.Linq.JToken DeepClone() => throw null;
        public static global::Newtonsoft.Json.Linq.JToken Parse(string json) => throw null;
        public static global::Newtonsoft.Json.Linq.JToken ReadFrom(global::Newtonsoft.Json.JsonReader reader) => throw null;
        public void Remove() => throw null;
        public T ToObject<T>() => throw null;
        public object ToObject(global::System.Type objectType) => throw null;
        public string ToString(global::Newtonsoft.Json.Formatting formatting, params global::Newtonsoft.Json.JsonConverter[] converters) => throw null;
        public virtual T Value<T>(object key) => throw null;
        public static explicit operator int(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static explicit operator long(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static explicit operator bool(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static explicit operator float(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static explicit operator string(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static explicit operator global::System.Nullable<bool>(global::Newtonsoft.Json.Linq.JToken value) => throw null;
        public static implicit operator global::Newtonsoft.Json.Linq.JToken(bool value) => throw null;
        public static implicit operator global::Newtonsoft.Json.Linq.JToken(string value) => throw null;
        public static implicit operator global::Newtonsoft.Json.Linq.JToken(float value) => throw null;
        public static implicit operator global::Newtonsoft.Json.Linq.JToken(int value) => throw null;
        public static implicit operator global::Newtonsoft.Json.Linq.JToken(long value) => throw null;
        protected JToken() { }
        global::System.Collections.Generic.IEnumerator<global::Newtonsoft.Json.Linq.JToken> global::System.Collections.Generic.IEnumerable<global::Newtonsoft.Json.Linq.JToken>.GetEnumerator() => throw null;
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => throw null;
    }
    public enum JTokenType : int {
        None = 0,
        Object = 1,
        Array = 2,
        Constructor = 3,
        Property = 4,
        Comment = 5,
        Integer = 6,
        Float = 7,
        String = 8,
        Boolean = 9,
        Null = 10,
        Undefined = 11,
        Date = 12,
        Raw = 13,
        Bytes = 14,
        Guid = 15,
        Uri = 16,
        TimeSpan = 17,
    }
    public unsafe partial class JValue : global::Newtonsoft.Json.Linq.JToken, global::System.IEquatable<global::Newtonsoft.Json.Linq.JValue>, global::System.IComparable<global::Newtonsoft.Json.Linq.JValue>, global::System.IConvertible {
        public object Value { get => throw null; set { } }
        protected JValue() { }
        int global::System.IComparable<global::Newtonsoft.Json.Linq.JValue>.CompareTo(global::Newtonsoft.Json.Linq.JValue other) => throw null;
        global::System.TypeCode global::System.IConvertible.GetTypeCode() => throw null;
        bool global::System.IConvertible.ToBoolean(global::System.IFormatProvider provider) => throw null;
        byte global::System.IConvertible.ToByte(global::System.IFormatProvider provider) => throw null;
        char global::System.IConvertible.ToChar(global::System.IFormatProvider provider) => throw null;
        global::System.DateTime global::System.IConvertible.ToDateTime(global::System.IFormatProvider provider) => throw null;
        decimal global::System.IConvertible.ToDecimal(global::System.IFormatProvider provider) => throw null;
        double global::System.IConvertible.ToDouble(global::System.IFormatProvider provider) => throw null;
        short global::System.IConvertible.ToInt16(global::System.IFormatProvider provider) => throw null;
        int global::System.IConvertible.ToInt32(global::System.IFormatProvider provider) => throw null;
        long global::System.IConvertible.ToInt64(global::System.IFormatProvider provider) => throw null;
        sbyte global::System.IConvertible.ToSByte(global::System.IFormatProvider provider) => throw null;
        float global::System.IConvertible.ToSingle(global::System.IFormatProvider provider) => throw null;
        string global::System.IConvertible.ToString(global::System.IFormatProvider provider) => throw null;
        object global::System.IConvertible.ToType(global::System.Type conversionType, global::System.IFormatProvider provider) => throw null;
        ushort global::System.IConvertible.ToUInt16(global::System.IFormatProvider provider) => throw null;
        uint global::System.IConvertible.ToUInt32(global::System.IFormatProvider provider) => throw null;
        ulong global::System.IConvertible.ToUInt64(global::System.IFormatProvider provider) => throw null;
        bool global::System.IEquatable<global::Newtonsoft.Json.Linq.JValue>.Equals(global::Newtonsoft.Json.Linq.JValue other) => throw null;
    }
}
