// <auto-generated>
//   Compile-only stand-in for "UnityModManager", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityModManagerNet {
    public unsafe partial class UnityModManager {
        protected UnityModManager() { }
        public unsafe partial class ModEntry {
            public readonly global::UnityModManagerNet.UnityModManager.ModEntry.ModLogger Logger;
            public global::System.Func<global::UnityModManagerNet.UnityModManager.ModEntry, bool, bool> OnToggle;
            public global::System.Func<global::UnityModManagerNet.UnityModManager.ModEntry, bool> OnUnload;
            public global::System.Action<global::UnityModManagerNet.UnityModManager.ModEntry, float> OnUpdate;
            public readonly string Path;
            protected ModEntry() { }
            public unsafe partial class ModLogger {
                public void Error(string str) => throw null;
                public void Log(string str) => throw null;
                public void Warning(string str) => throw null;
                protected ModLogger() { }
            }
        }
    }
}
