// <auto-generated>
//   Compile-only stand-in for "UnityEngine.UIModule", generated by tools/StubGen.
//
//   Every declaration below exists because Quartz's own compiled IL names it.
//   The set is derived from OUR usage, not copied from the game: no method
//   bodies, no constants beyond the ones our code reads, no resources, no
//   types we never touch. It exists so CI can compile the whole mod without a
//   game install, and it is never shipped or loaded at runtime.
//
//   Do not edit by hand. Run tools/gen-stubs.sh against a real install.
// </auto-generated>
#pragma warning disable CS0067, CS0169, CS0649, CS0108, CS0109, CS0114, CS0465, CS0824

namespace UnityEngine {
    public sealed unsafe partial class Canvas : global::UnityEngine.Behaviour {
        public bool overrideSorting { get => throw null; set { } }
        public bool pixelPerfect { get => throw null; set { } }
        public global::UnityEngine.RenderMode renderMode { get => throw null; set { } }
        public int sortingOrder { get => throw null; set { } }
        public global::UnityEngine.Camera worldCamera { get => throw null; set { } }
        public static event global::UnityEngine.Canvas.WillRenderCanvases willRenderCanvases { add { } remove { } }
        public static void ForceUpdateCanvases() => throw null;
        public static global::UnityEngine.Material GetDefaultCanvasMaterial() => throw null;
        private Canvas() { }
        public unsafe delegate void WillRenderCanvases();
    }
    public sealed unsafe partial class CanvasGroup : global::UnityEngine.Behaviour {
        public float alpha { get => throw null; set { } }
        public bool blocksRaycasts { get => throw null; set { } }
        public bool interactable { get => throw null; set { } }
        private CanvasGroup() { }
    }
    public sealed unsafe partial class CanvasRenderer : global::UnityEngine.Component {
        public bool cullTransparentMesh { get => throw null; set { } }
        public float GetAlpha() => throw null;
        public void SetAlpha(float alpha) => throw null;
        private CanvasRenderer() { }
    }
    public unsafe partial interface ICanvasRaycastFilter {
    }
    public sealed unsafe partial class RectTransformUtility {
        public static bool RectangleContainsScreenPoint(global::UnityEngine.RectTransform rect, global::UnityEngine.Vector2 screenPoint, global::UnityEngine.Camera cam) => throw null;
        public static bool ScreenPointToLocalPointInRectangle(global::UnityEngine.RectTransform rect, global::UnityEngine.Vector2 screenPoint, global::UnityEngine.Camera cam, out global::UnityEngine.Vector2 localPoint) => throw null;
        public static global::UnityEngine.Vector2 WorldToScreenPoint(global::UnityEngine.Camera cam, global::UnityEngine.Vector3 worldPoint) => throw null;
        private RectTransformUtility() { }
    }
    public enum RenderMode : int {
        ScreenSpaceOverlay = 0,
        ScreenSpaceCamera = 1,
        WorldSpace = 2,
    }
}
