List<(string Name, Action Run)> tests = [
    ("SemVer parses and orders channels", SemVerTests.TestSemVer),
    ("SemVer formats and parses channels", SemVerTests.TestSemVerFormatAndChannels),
    ("AtomicFile replaces without temp debris", AtomicFileTests.TestAtomicFile),
    ("Imported mod profile names are sanitized and uniquified", ProfileNamesTests.TestImportedModProfileNames),
    ("Preset import drops the fields a preset may not impose", ProfileBundleTests.TestPresetStripsImposedFields),
    ("Preset import passes every other file through untouched", ProfileBundleTests.TestPresetLeavesOtherFilesByteIdentical),
    ("Importing an exported profile keeps its Language", ProfileBundleTests.TestImportButtonKeepsLanguage),
    ("Localization keys stay in parity", LocalizationParityTests.TestLocalizationParity),
    ("KeyViewer CSS parses the DM Note contract", KeyViewerCssTests.TestKeyViewerCss),
    ("KeyViewer CSS parses the extended web effects", KeyViewerCssTests.TestKeyViewerCssExtended),
    ("KeyViewer persistence avoids gameplay saves and strips unused preset data", KeyViewerCssTests.TestKeyViewerPersistence),
    ("KeyViewer layout round-trips data DM Note models but Quartz does not", KvDocumentTests.TestRoundTripPreservesUnmodelledData),
    ("KeyViewer layout keeps keys[] and keyPositions[] parallel", KvDocumentTests.TestRoundTripKeepsArraysParallel),
    ("KeyViewer authored elements carry DM Note's required fields", KvDocumentTests.TestAuthoredElementsCarryRequiredFields),
    ("KeyViewer layout rejects non-presets and normalizes legacy positions", KvDocumentTests.TestParseRejectsNonPresets),
    ("KeyViewer export writes DM Note's integer fields as integers", KvDocumentTests.TestIntegerFieldsNeverSerializeAsFloats),
    ("KeyViewer generated layout passes DM Note's import contract", KvDocumentTests.TestGeneratedLayoutPassesDmNoteImport),
    ("KeyViewer DM Note import validator catches a float integer field", KvDocumentTests.TestDmNoteImportValidatorCatchesFloatIntField),
    ("KeyViewer .qkv keeps what the DM Note export has to give up", KvDocumentTests.TestExportFormatsSplitQuartzOnlyData),
    ("KeyViewer DM Note export warns only about what the layout uses", KvDocumentTests.TestDmNoteGapsReportOnlyWhatIsUsed),
    ("KeyViewer DM Note gap scan ignores a switched-off note shadow", KvDocumentTests.TestDmNoteGapsIgnoreDisabledNoteShadow),
    ("KeyViewer foot keys carry an explicit marker that round-trips", KvDocumentTests.TestFootMarkerIsExplicitAndRoundTrips),
    ("KeyViewer per-key KPS is absent by default and round-trips", KvDocumentTests.TestPerKeyKpsIsOptOutAndRoundTrips),
    ("KeyViewer tabs are created, named uniquely, and removed", KvDocumentTests.TestTabsCreateNameAndRemove),
    ("KeyViewer tab rename is unique, reversible, and round-trips", KvDocumentTests.TestRenameTabIsUniqueAndReversible),
    ("KeyViewer import surfaces a preset's embedded custom CSS", KvDocumentTests.TestEmbeddedCssIsExtractedForImport),
    ("KeyViewer import merges tabs, keeping the existing ones", KvDocumentTests.TestMergeKeepsExistingTabsAndAddsImported),
    ("KeyViewer tab removal leaves unmodelled tables alone", KvDocumentTests.TestRemoveTabLeavesUnmodelledTablesAlone),
    ("KeyViewer render anchor persists and dies with its tab", KvDocumentTests.TestRenderAnchorPersistsAndDiesWithItsTab),
    ("KeyViewer key-limiter sync sees only the keys the viewer draws", KvDocumentTests.TestBoundKeyElementsMatchWhatTheViewerDraws),
    ("KeyViewer editor grid step tracks zoom", KvSnapTests.TestGridStepTracksZoom),
    ("KeyViewer editor zoom clamps to DM Note's range", KvSnapTests.TestZoomClamps),
    ("KeyViewer editor shift-drag axis lock matches DM Note", KvSnapTests.TestShiftAxisLockMatchesDmNote),
    ("KeyViewer editor drag snaps to the grid", KvSnapTests.TestMoveSnapsToGridWithoutNeighbours),
    ("KeyViewer editor alignment beats grid and emits guides", KvSnapTests.TestAlignmentBeatsGridAndEmitsGuides),
    ("KeyViewer editor ignores neighbours beyond the align threshold", KvSnapTests.TestAlignmentIgnoresDistantNeighbours),
    ("KeyViewer editor drag clamps to layout bounds", KvSnapTests.TestMoveClampsToLayoutBounds),
    ("KeyViewer editor resize matches sibling sizes and floors", KvSnapTests.TestSizeSnapMatchesSiblingsAndFloors),
    ("KeyViewer editor marquee selects on intersection", KvSnapTests.TestMarqueeSelectsOnIntersection),
    ("KeyViewer editor scroll pans on both axes", KvSnapTests.TestWheelPanHonoursBothAxes),
    ("KeyViewer editor scroll pan axes do not share a sign", KvSnapTests.TestWheelPanAxesDoNotShareASign),
    ("KeyViewer editor pan speed is not the page scroll speed", KvSnapTests.TestPanSpeedIsNotThePageScrollSpeed),
    ("KeyViewer editor zoom step scales with scroll distance", KvSnapTests.TestZoomStepScalesWithScrollDistance),
    ("KeyViewer editor shift-wheel pans horizontally but defers to a trackpad", KvSnapTests.TestShiftWheelPansHorizontallyButDefersToATrackpad),
    ("KeyViewer editor wheel deadzone keeps a slow trackpad scroll", KvSnapTests.TestWheelDeadzoneIgnoresNoiseButNotASlowTrackpad),
    ("KeyViewer editor undo and redo walk both ways", KvHistoryTests.TestUndoRedoWalksBothWays),
    ("KeyViewer editor editing after undo discards redo", KvHistoryTests.TestEditAfterUndoDiscardsRedo),
    ("KeyViewer editor history drops the oldest entry on overflow", KvHistoryTests.TestDepthDropsOldestNotNewest),
    ("KeyViewer editor held nudges coalesce into one undo step", KvHistoryTests.TestHeldNudgeCoalescesToOneStep),
    ("TUF inputs and download URLs are validated", TufSecurityTests.TestInputAndNetworkPolicy),
    ("TUF archives reject unsafe entries and select charts", TufSecurityTests.TestArchiveSafetyAndSelection),
    ("TUF difficulty filters clamp, select, and reset", TufFilterTests.TestDifficultyFilterContract),
    ("TUF API emits named PGU and special filters", TufFilterTests.TestApiDifficultyQuery),
    ("TUF quantum range selects, clamps, and clears", TufFilterTests.TestQuantumRange),
    ("TUF browser preferences serialize and normalize", TufFilterTests.TestPersistedPreferences),
    ("TUF free-space probe fails open when the volume is unknown", TufDiskSpaceTests.TestSpaceProbeFailsOpen),
    ("TUF sizes are worded for humans", TufDiskSpaceTests.TestSizeWording),
    ("TUF archives declare their expanded size instead of hitting a ceiling", TufDiskSpaceTests.TestDeclaredSize),
    ("TUF level folder names are recognized strictly", TufInstallTests.TestLevelFolderNaming),
    ("TUF delete only ever targets folders it owns", TufInstallTests.TestDeleteGuard),
    ("TUF library roots reject volumes and folders holding user files", TufInstallTests.TestLibraryRootValidation),
    ("TUF nested library roots are detected", TufInstallTests.TestNestedRoots),
    ("TUF install index records, moves, and round-trips", TufInstallTests.TestInstallIndexRoundTrip),
    ("TUF install index rejects corrupt records", TufInstallTests.TestInstallIndexRejectsJunk),
    ("TUF install index adopts orphans and prunes missing", TufInstallTests.TestAdoptAndPrune),
    ("TUF reads song info straight out of an installed chart", TufChartInfoTests.TestReadsSettingsAfterChartData),
    ("TUF ignores charts it cannot read info from", TufChartInfoTests.TestRejectsUnreadableCharts),
    ("TUF install entries merge chart and API info", TufChartInfoTests.TestEntryMetadataMerge),
    ("TUF pack list parses string ids and counts", TufPackParseTests.TestPackListParsing),
    ("TUF pack tree flattens, dedups, and credits charters", TufPackParseTests.TestPackTreeParsing),
];
int failed = 0;
foreach((string name, Action run) in tests) {
    try {
        run();
        Console.WriteLine("PASS " + name);
    } catch(Exception e) {
        failed++;
        Console.Error.WriteLine("FAIL " + name + ": " + e.Message);
    }
}
return failed == 0 ? 0 : 1;
