List<(string Name, Action Run)> tests = [
    ("SemVer parses and orders channels", SemVerTests.TestSemVer),
    ("SemVer formats and parses channels", SemVerTests.TestSemVerFormatAndChannels),
    ("AtomicFile replaces without temp debris", AtomicFileTests.TestAtomicFile),
    ("Diag counts deliberate swallows without logging them", DiagTests.TestIgnoreIsCountedAndSilentByDefault),
    ("Diag verbose mode surfaces swallowed exceptions", DiagTests.TestVerboseSurfacesIgnoredExceptions),
    ("Diag warnings always reach the log with their context", DiagTests.TestWarnAlwaysReachesTheSink),
    ("Diag warnings without a context still identify themselves", DiagTests.TestWarnWithoutContextStillIdentifiesItself),
    ("Diag describes a null exception instead of dereferencing it", DiagTests.TestNullExceptionIsDescribedNotDereferenced),
    ("Diag counts a failing logger instead of propagating it", DiagTests.TestAFailingSinkIsCountedNotPropagated),
    ("Diag works before a logger is bound", DiagTests.TestUnboundDiagIsSafe),
    ("Refl resolves inherited, private, and static members", ReflTests.TestResolvesPropertiesAndFields),
    ("Refl resolves an ambiguous member to its nearest declaration", ReflTests.TestAmbiguousMemberFallsBackToTheNearestDeclaration),
    ("Refl takes the first name that exists from a candidate list", ReflTests.TestNameListTakesTheFirstThatExists),
    ("Refl treats a member the game removed as inert, not fatal", ReflTests.TestMissingMembersAreInertNotFatal),
    ("Refl never mistakes an indexer for a member", ReflTests.TestIndexersAreNeverTreatedAsMembers),
    ("Refl typed reads fall back when the game changed a type", ReflTests.TestTypedGetFallsBackOnMismatch),
    ("Refl writes land, and an unwritable target is inert", ReflTests.TestWritesGoThroughAndUnwritableTargetsAreInert),
    ("Refl swallows a game property getter that throws", ReflTests.TestThrowingMembersAreSwallowedNotPropagated),
    ("Refl selects methods by argument count", ReflTests.TestMethodSelectionByArgCount),
    ("Refl matches a shorter call when the tail is optional", ReflTests.TestOptionalParametersSatisfyAShorterArgCount),
    ("Refl caches method lookups, hits and misses alike", ReflTests.TestMethodLookupIsCached),
    ("Refl pads omitted optional arguments with their defaults", ReflTests.TestInvokePadsMissingOptionalArguments),
    ("Refl invocation is inert on null and throwing targets", ReflTests.TestInvokeIsInertOnNullAndThrowingTargets),
    ("Imported mod profile names are sanitized and uniquified", ProfileNamesTests.TestImportedModProfileNames),
    ("Preset import drops the fields a preset may not impose", ProfileBundleTests.TestPresetStripsImposedFields),
    ("Preset import passes every other file through untouched", ProfileBundleTests.TestPresetLeavesOtherFilesByteIdentical),
    ("Importing an exported profile keeps its Language", ProfileBundleTests.TestImportButtonKeepsLanguage),
    ("Localization keys stay in parity", LocalizationParityTests.TestLocalizationParity),
    ("FAQ ships a usable default in every language it claims", FaqDocumentTests.TestShippedDefaultIsUsable),
    ("FAQ text falls back exact language then en-US then anything", FaqDocumentTests.TestLanguagePicksExactThenEnglishThenAnything),
    ("FAQ reads the shapes a user is likely to hand-write", FaqDocumentTests.TestShapesUsersAreLikelyToWrite),
    ("FAQ parser is quiet on empty files and loud on broken ones", FaqDocumentTests.TestUnreadableFilesDoNotThrowPastTheParser),
    ("KeyViewer CSS parses the DM Note contract", KeyViewerCssTests.TestKeyViewerCss),
    ("KeyViewer CSS parses the extended web effects", KeyViewerCssTests.TestKeyViewerCssExtended),
    ("KeyViewer persistence avoids gameplay saves and strips unused preset data", KeyViewerCssTests.TestKeyViewerPersistence),
    ("KeyViewer layout round-trips data DM Note models but Quartz does not", KvDocumentTests.TestRoundTripPreservesUnmodelledData),
    ("KeyViewer layout keeps keys[] and keyPositions[] parallel", KvDocumentTests.TestRoundTripKeepsArraysParallel),
    ("KeyViewer authored elements carry DM Note's required fields", KvDocumentTests.TestAuthoredElementsCarryRequiredFields),
    ("KeyViewer layout rejects non-presets and normalizes legacy positions", KvDocumentTests.TestParseRejectsNonPresets),
    ("KeyViewer export writes DM Note's integer fields as integers", KvDocumentTests.TestIntegerFieldsNeverSerializeAsFloats),
    ("KeyViewer generated layout passes DM Note's import contract", KvDocumentTests.TestGeneratedLayoutPassesDmNoteImport),
    ("KeyViewer DM Note import validator catches a float integer field", KvDocumentTests.TestDmNoteImportValidatorCatchesFloatIntField),
    ("KeyViewer .qkv keeps what the DM Note export has to give up", KvDocumentTests.TestExportFormatsSplitQuartzOnlyData),
    ("KeyViewer DM Note export warns only about what the layout uses", KvDocumentTests.TestDmNoteGapsReportOnlyWhatIsUsed),
    ("KeyViewer DM Note gap scan ignores a switched-off note shadow", KvDocumentTests.TestDmNoteGapsIgnoreDisabledNoteShadow),
    ("KeyViewer foot keys carry an explicit marker that round-trips", KvDocumentTests.TestFootMarkerIsExplicitAndRoundTrips),
    ("KeyViewer per-key KPS is absent by default and round-trips", KvDocumentTests.TestPerKeyKpsIsOptOutAndRoundTrips),
    ("KeyViewer tabs are created, named uniquely, and removed", KvDocumentTests.TestTabsCreateNameAndRemove),
    ("KeyViewer tab rename is unique, reversible, and round-trips", KvDocumentTests.TestRenameTabIsUniqueAndReversible),
    ("KeyViewer import surfaces a preset's embedded custom CSS", KvDocumentTests.TestEmbeddedCssIsExtractedForImport),
    ("KeyViewer import merges tabs, keeping the existing ones", KvDocumentTests.TestMergeKeepsExistingTabsAndAddsImported),
    ("KeyViewer tab removal leaves unmodelled tables alone", KvDocumentTests.TestRemoveTabLeavesUnmodelledTablesAlone),
    ("KeyViewer render anchor persists and dies with its tab", KvDocumentTests.TestRenderAnchorPersistsAndDiesWithItsTab),
    ("KeyViewer key-limiter sync sees only the keys the viewer draws", KvDocumentTests.TestBoundKeyElementsMatchWhatTheViewerDraws),
    ("Module manifest parses, validates, and refuses future schemas", ModuleManifestTests.TestManifestParsesAndValidates),
    ("Module manifest rejects unsafe ids and self-dependencies", ModuleManifestTests.TestManifestRejectsUnsafeIds),
    ("Module install state round-trips and survives corruption", ModuleManifestTests.TestModuleStateRoundTrips),
    ("Module dependencies load before their dependents", ModuleOrderTests.TestDependenciesLoadBeforeDependents),
    ("Module load order is deterministic", ModuleOrderTests.TestOrderIsDeterministic),
    ("A missing module dependency cascade-skips its dependents", ModuleOrderTests.TestMissingDependencyCascades),
    ("A module dependency cycle rejects every member", ModuleOrderTests.TestCycleRejectsEveryMember),
    ("A fresh install migrates to core only", ModuleMigrationTests.TestFreshInstallStaysCoreOnly),
    ("An upgrade keeps the features it had enabled", ModuleMigrationTests.TestUpgradeKeepsEnabledFeaturesAndDropsDisabledOnes),
    ("A missing settings file migrates on the feature's own default", ModuleMigrationTests.TestAbsentFileFallsBackToTheFeatureDefault),
    ("Malformed or partial settings migrate on the default", ModuleMigrationTests.TestMalformedOrPartialSettingsUseTheDefault),
    ("Features with no master toggle always come along", ModuleMigrationTests.TestFeaturesWithNoMasterToggleAlwaysComeAlong),
    ("Judgement and Hide Judgements carry over separately", ModuleMigrationTests.TestJudgementAndHideJudgementsCarryOverSeparately),
    ("An unreadable settings file never stops the migration", ModuleMigrationTests.TestAnUnreadableSettingsFileNeverStopsTheMigration),
    ("Every migration rule targets a valid module id", ModuleMigrationTests.TestEveryRuleTargetsAValidModuleId),
    ("Every module split targets valid module ids", ModuleMigrationTests.TestEverySplitTargetsValidModuleIds),
    ("KeyViewer class and inline-style priority round-trip on flat and nested elements", KvDocumentTests.TestClassAndInlinePriorityRoundTrip),
    ("KeyViewer export carries only the selected tab", KvDocumentTests.TestExportKeepsOnlyTheSelectedTab),
    ("KeyViewer editor grid step tracks zoom", KvSnapTests.TestGridStepTracksZoom),
    ("KeyViewer editor zoom clamps to DM Note's range", KvSnapTests.TestZoomClamps),
    ("KeyViewer editor shift-drag axis lock matches DM Note", KvSnapTests.TestShiftAxisLockMatchesDmNote),
    ("KeyViewer editor drag snaps to the grid", KvSnapTests.TestMoveSnapsToGridWithoutNeighbours),
    ("KeyViewer editor alignment beats grid and emits guides", KvSnapTests.TestAlignmentBeatsGridAndEmitsGuides),
    ("KeyViewer editor ignores neighbours beyond the align threshold", KvSnapTests.TestAlignmentIgnoresDistantNeighbours),
    ("KeyViewer editor drag clamps to layout bounds", KvSnapTests.TestMoveClampsToLayoutBounds),
    ("KeyViewer editor resize matches sibling sizes and floors", KvSnapTests.TestSizeSnapMatchesSiblingsAndFloors),
    ("KeyViewer editor marquee selects on intersection", KvSnapTests.TestMarqueeSelectsOnIntersection),
    ("KeyViewer editor scroll pans on both axes", KvSnapTests.TestWheelPanHonoursBothAxes),
    ("KeyViewer editor scroll pan axes do not share a sign", KvSnapTests.TestWheelPanAxesDoNotShareASign),
    ("KeyViewer editor pan speed is not the page scroll speed", KvSnapTests.TestPanSpeedIsNotThePageScrollSpeed),
    ("KeyViewer editor zoom step scales with scroll distance", KvSnapTests.TestZoomStepScalesWithScrollDistance),
    ("KeyViewer editor shift-wheel pans horizontally but defers to a trackpad", KvSnapTests.TestShiftWheelPansHorizontallyButDefersToATrackpad),
    ("KeyViewer editor wheel deadzone keeps a slow trackpad scroll", KvSnapTests.TestWheelDeadzoneIgnoresNoiseButNotASlowTrackpad),
    ("KeyViewer editor undo and redo walk both ways", KvHistoryTests.TestUndoRedoWalksBothWays),
    ("KeyViewer editor editing after undo discards redo", KvHistoryTests.TestEditAfterUndoDiscardsRedo),
    ("KeyViewer editor history drops the oldest entry on overflow", KvHistoryTests.TestDepthDropsOldestNotNewest),
    ("KeyViewer editor held nudges coalesce into one undo step", KvHistoryTests.TestHeldNudgeCoalescesToOneStep),
    ("TUF inputs and download URLs are validated", TufSecurityTests.TestInputAndNetworkPolicy),
    ("TUF archives reject unsafe entries and select charts", TufSecurityTests.TestArchiveSafetyAndSelection),
    ("TUF difficulty filters clamp, select, and reset", TufFilterTests.TestDifficultyFilterContract),
    ("TUF API emits named PGU and special filters", TufFilterTests.TestApiDifficultyQuery),
    ("TUF quantum range selects, clamps, and clears", TufFilterTests.TestQuantumRange),
    ("TUF browser preferences serialize and normalize", TufFilterTests.TestPersistedPreferences),
    ("TUF free-space probe fails open when the volume is unknown", TufDiskSpaceTests.TestSpaceProbeFailsOpen),
    ("TUF sizes are worded for humans", TufDiskSpaceTests.TestSizeWording),
    ("TUF archives declare their expanded size instead of hitting a ceiling", TufDiskSpaceTests.TestDeclaredSize),
    ("TUF level folder names are recognized strictly", TufInstallTests.TestLevelFolderNaming),
    ("TUF delete only ever targets folders it owns", TufInstallTests.TestDeleteGuard),
    ("TUF library roots reject volumes and folders holding user files", TufInstallTests.TestLibraryRootValidation),
    ("TUF nested library roots are detected", TufInstallTests.TestNestedRoots),
    ("TUF install index records, moves, and round-trips", TufInstallTests.TestInstallIndexRoundTrip),
    ("TUF install index rejects corrupt records", TufInstallTests.TestInstallIndexRejectsJunk),
    ("TUF install index adopts orphans and prunes missing", TufInstallTests.TestAdoptAndPrune),
    ("TUF reads song info straight out of an installed chart", TufChartInfoTests.TestReadsSettingsAfterChartData),
    ("TUF ignores charts it cannot read info from", TufChartInfoTests.TestRejectsUnreadableCharts),
    ("TUF install entries merge chart and API info", TufChartInfoTests.TestEntryMetadataMerge),
    ("TUF pack list parses string ids and counts", TufPackParseTests.TestPackListParsing),
    ("TUF pack tree flattens, dedups, and credits charters", TufPackParseTests.TestPackTreeParsing),
];
int failed = 0;
foreach((string name, Action run) in tests) {
    try {
        run();
        Console.WriteLine("PASS " + name);
    } catch(Exception e) {
        failed++;
        Console.Error.WriteLine("FAIL " + name + ": " + e.Message);
    }
}
return failed == 0 ? 0 : 1;
